"""Document domain event types."""

from enum import StrEnum


class DocumentEventType(StrEnum):
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    PORTAL_DOCUMENT_UPLOADED = "PORTAL_DOCUMENT_UPLOADED"
    DOCUMENT_VERSION_CREATED = "DOCUMENT_VERSION_CREATED"
    OCR_COMPLETED = "OCR_COMPLETED"
    CLASSIFICATION_COMPLETED = "CLASSIFICATION_COMPLETED"
    METADATA_EXTRACTED = "METADATA_EXTRACTED"
    ENTITY_RESOLVED = "ENTITY_RESOLVED"
