import type {
  AutomationRule,
  BorrowerRecord,
  CalendarEvent,
  CrmDocument,
  CrmNote,
  CrmReportingSnapshot,
  CrmTask,
  EmailMessage,
  LenderContact,
  PartnerOrg,
  PipelineCard,
  RealtorContact,
  ReferralRecord,
  SmsMessage,
  WorkflowStep,
} from '@/lib/crm/types';
import type { CrmRole } from '@/lib/crm/types';

export const DEMO_USERS: Array<{
  id: string;
  email: string;
  password: string;
  displayName: string;
  role: CrmRole;
  organizationId: string;
  organizationName: string;
  title: string;
}> = [
  {
    id: 'crm-u-admin',
    email: 'admin@lrp.crm',
    password: 'changeme123',
    displayName: 'Avery Chen',
    role: 'crm_admin',
    organizationId: 'org-lrp-ops',
    organizationName: 'Lending Readiness Partners',
    title: 'CRM Administrator',
  },
  {
    id: 'crm-u-pm',
    email: 'partners@lrp.crm',
    password: 'changeme123',
    displayName: 'Jordan Hale',
    role: 'partner_manager',
    organizationId: 'org-lrp-ops',
    organizationName: 'Lending Readiness Partners',
    title: 'Partner Manager',
  },
  {
    id: 'crm-u-lo',
    email: 'lo@lrp.crm',
    password: 'changeme123',
    displayName: 'Morgan Ellis',
    role: 'loan_officer',
    organizationId: 'org-lrp-ops',
    organizationName: 'Lending Readiness Partners',
    title: 'Loan Officer',
  },
  {
    id: 'crm-u-rl',
    email: 'realtor@lrp.crm',
    password: 'changeme123',
    displayName: 'Casey Brooks',
    role: 'realtor_liaison',
    organizationId: 'org-lrp-ops',
    organizationName: 'Lending Readiness Partners',
    title: 'Realtor Liaison',
  },
  {
    id: 'crm-u-ops',
    email: 'ops@lrp.crm',
    password: 'changeme123',
    displayName: 'Riley Quinn',
    role: 'ops_coordinator',
    organizationId: 'org-lrp-ops',
    organizationName: 'Lending Readiness Partners',
    title: 'Ops Coordinator',
  },
  {
    id: 'crm-u-ro',
    email: 'readonly@lrp.crm',
    password: 'changeme123',
    displayName: 'Sam Rivera',
    role: 'read_only',
    organizationId: 'org-lrp-ops',
    organizationName: 'Lending Readiness Partners',
    title: 'Analyst (read only)',
  },
];

export const partners: PartnerOrg[] = [
  {
    id: 'p-harbor',
    name: 'Harbor Home Mortgage',
    type: 'lender',
    status: 'active',
    primaryContact: 'Dana Whitfield',
    email: 'dana@harborhome.demo',
    phone: '(404) 555-0142',
    market: 'Atlanta MSA',
    activeReferrals: 18,
    fundedYtd: 42,
    ownerName: 'Jordan Hale',
    lastActivityAt: '2026-07-21T14:20:00Z',
    notes: 'Primary lender channel. Weekly readiness sync Fridays.',
  },
  {
    id: 'p-summit',
    name: 'Summit Realty Group',
    type: 'realtor',
    status: 'active',
    primaryContact: 'Pat Okonkwo',
    email: 'pat@summitrealty.demo',
    phone: '(770) 555-0198',
    market: 'North Metro Atlanta',
    activeReferrals: 11,
    fundedYtd: 19,
    ownerName: 'Casey Brooks',
    lastActivityAt: '2026-07-20T18:05:00Z',
    notes: 'Prefers SMS updates on near-ready borrowers.',
  },
  {
    id: 'p-crest',
    name: 'Crestline Credit Ops',
    type: 'operator',
    status: 'active',
    primaryContact: 'Lee Nakamura',
    email: 'lee@crestline.demo',
    phone: '(678) 555-0110',
    market: 'Southeast',
    activeReferrals: 7,
    fundedYtd: 28,
    ownerName: 'Avery Chen',
    lastActivityAt: '2026-07-19T12:00:00Z',
    notes: 'White-label operator using LRP readiness packaging.',
  },
  {
    id: 'p-oak',
    name: 'Oak & Pine Brokers',
    type: 'broker',
    status: 'prospect',
    primaryContact: 'Taylor Sims',
    email: 'taylor@oakpine.demo',
    phone: '(404) 555-0177',
    market: 'Savannah',
    activeReferrals: 0,
    fundedYtd: 0,
    ownerName: 'Jordan Hale',
    lastActivityAt: '2026-07-15T09:30:00Z',
    notes: 'Discovery call scheduled; Partner Kit pending.',
  },
  {
    id: 'p-river',
    name: 'Riverbend Lending',
    type: 'lender',
    status: 'paused',
    primaryContact: 'Chris Alvarez',
    email: 'chris@riverbend.demo',
    phone: '(912) 555-0133',
    market: 'Coastal GA',
    activeReferrals: 2,
    fundedYtd: 9,
    ownerName: 'Morgan Ellis',
    lastActivityAt: '2026-06-28T16:45:00Z',
    notes: 'Paused pending compliance review of referral SLA.',
  },
];

export const lenders: LenderContact[] = [
  {
    id: 'l-dana',
    organizationId: 'p-harbor',
    organizationName: 'Harbor Home Mortgage',
    displayName: 'Dana Whitfield',
    email: 'dana@harborhome.demo',
    phone: '(404) 555-0142',
    title: 'Senior Loan Officer',
    nmls: '123456',
    activeBorrowers: 14,
    openReferrals: 5,
    market: 'Atlanta',
    status: 'active',
  },
  {
    id: 'l-jamie',
    organizationId: 'p-harbor',
    organizationName: 'Harbor Home Mortgage',
    displayName: 'Jamie Ortiz',
    email: 'jamie@harborhome.demo',
    phone: '(404) 555-0143',
    title: 'Loan Officer',
    nmls: '234567',
    activeBorrowers: 9,
    openReferrals: 3,
    market: 'Atlanta',
    status: 'active',
  },
  {
    id: 'l-chris',
    organizationId: 'p-river',
    organizationName: 'Riverbend Lending',
    displayName: 'Chris Alvarez',
    email: 'chris@riverbend.demo',
    phone: '(912) 555-0133',
    title: 'Branch Manager',
    nmls: '345678',
    activeBorrowers: 2,
    openReferrals: 1,
    market: 'Savannah',
    status: 'inactive',
  },
];

export const realtors: RealtorContact[] = [
  {
    id: 'r-pat',
    brokerage: 'Summit Realty Group',
    displayName: 'Pat Okonkwo',
    email: 'pat@summitrealty.demo',
    phone: '(770) 555-0198',
    market: 'Alpharetta',
    activeBorrowers: 8,
    openReferrals: 4,
    status: 'active',
    preferredLender: 'Harbor Home Mortgage',
  },
  {
    id: 'r-nina',
    brokerage: 'Summit Realty Group',
    displayName: 'Nina Patel',
    email: 'nina@summitrealty.demo',
    phone: '(770) 555-0199',
    market: 'Roswell',
    activeBorrowers: 5,
    openReferrals: 2,
    status: 'active',
    preferredLender: 'Harbor Home Mortgage',
  },
  {
    id: 'r-drew',
    brokerage: 'Coastal Nest Realty',
    displayName: 'Drew Mason',
    email: 'drew@coastalnest.demo',
    phone: '(912) 555-0188',
    market: 'Savannah',
    activeBorrowers: 1,
    openReferrals: 1,
    status: 'inactive',
    preferredLender: null,
  },
];

export const borrowers: BorrowerRecord[] = [
  {
    id: 'b-1',
    displayName: 'Alex Rivera',
    email: 'alex.rivera@example.com',
    phone: '(404) 555-1001',
    stage: 'in_repair',
    readinessScore: 62,
    readinessBand: 'Building',
    lenderId: 'l-dana',
    lenderName: 'Dana Whitfield',
    realtorId: 'r-pat',
    realtorName: 'Pat Okonkwo',
    partnerId: 'p-harbor',
    loName: 'Morgan Ellis',
    estimatedReadyDate: '2026-09-15',
    progressPct: 48,
    loanGoal: 'Conventional purchase',
    source: 'Lender referral',
    lastActivityAt: '2026-07-21T11:00:00Z',
    blockers: ['Collection balance > $500', 'Utilization above 45%'],
  },
  {
    id: 'b-2',
    displayName: 'Blake Nguyen',
    email: 'blake.nguyen@example.com',
    phone: '(770) 555-1002',
    stage: 'near_ready',
    readinessScore: 78,
    readinessBand: 'Near ready',
    lenderId: 'l-jamie',
    lenderName: 'Jamie Ortiz',
    realtorId: 'r-nina',
    realtorName: 'Nina Patel',
    partnerId: 'p-harbor',
    loName: 'Morgan Ellis',
    estimatedReadyDate: '2026-08-10',
    progressPct: 81,
    loanGoal: 'FHA purchase',
    source: 'Realtor referral',
    lastActivityAt: '2026-07-22T08:30:00Z',
    blockers: ['One late payment within 12 months'],
  },
  {
    id: 'b-3',
    displayName: 'Cameron Brooks',
    email: 'cameron.brooks@example.com',
    phone: '(678) 555-1003',
    stage: 'mortgage_ready',
    readinessScore: 88,
    readinessBand: 'Mortgage ready',
    lenderId: 'l-dana',
    lenderName: 'Dana Whitfield',
    realtorId: null,
    realtorName: null,
    partnerId: 'p-harbor',
    loName: 'Morgan Ellis',
    estimatedReadyDate: '2026-07-28',
    progressPct: 94,
    loanGoal: 'Refinance',
    source: 'Partner kit',
    lastActivityAt: '2026-07-21T16:10:00Z',
    blockers: [],
  },
  {
    id: 'b-4',
    displayName: 'Devon Shah',
    email: 'devon.shah@example.com',
    phone: '(404) 555-1004',
    stage: 'intake',
    readinessScore: 41,
    readinessBand: 'Early',
    lenderId: null,
    lenderName: null,
    realtorId: 'r-pat',
    realtorName: 'Pat Okonkwo',
    partnerId: 'p-summit',
    loName: 'Riley Quinn',
    estimatedReadyDate: '2026-11-01',
    progressPct: 22,
    loanGoal: 'First-time purchase',
    source: 'Realtor referral',
    lastActivityAt: '2026-07-18T13:20:00Z',
    blockers: ['Missing tri-bureau reports', 'Identity docs pending'],
  },
  {
    id: 'b-5',
    displayName: 'Ellis Park',
    email: 'ellis.park@example.com',
    phone: '(912) 555-1005',
    stage: 'qualified',
    readinessScore: 55,
    readinessBand: 'Building',
    lenderId: 'l-chris',
    lenderName: 'Chris Alvarez',
    realtorId: 'r-drew',
    realtorName: 'Drew Mason',
    partnerId: 'p-river',
    loName: 'Morgan Ellis',
    estimatedReadyDate: null,
    progressPct: 30,
    loanGoal: 'VA purchase',
    source: 'Web lead',
    lastActivityAt: '2026-07-12T10:00:00Z',
    blockers: ['Partner channel paused'],
  },
  {
    id: 'b-6',
    displayName: 'Frankie Cole',
    email: 'frankie.cole@example.com',
    phone: '(404) 555-1006',
    stage: 'in_underwriting',
    readinessScore: 91,
    readinessBand: 'Mortgage ready',
    lenderId: 'l-dana',
    lenderName: 'Dana Whitfield',
    realtorId: 'r-nina',
    realtorName: 'Nina Patel',
    partnerId: 'p-harbor',
    loName: 'Morgan Ellis',
    estimatedReadyDate: '2026-07-20',
    progressPct: 97,
    loanGoal: 'Conventional purchase',
    source: 'Lender referral',
    lastActivityAt: '2026-07-22T09:15:00Z',
    blockers: [],
  },
];

export const pipelineCards: PipelineCard[] = borrowers.map((b, i) => ({
  id: `pc-${b.id}`,
  borrowerId: b.id,
  borrowerName: b.displayName,
  stage: b.stage,
  readinessScore: b.readinessScore,
  loName: b.loName,
  partnerName: partners.find((p) => p.id === b.partnerId)?.name ?? 'Direct',
  daysInStage: [12, 8, 4, 3, 15, 6][i] ?? 5,
  estimatedReadyDate: b.estimatedReadyDate,
}));

export const tasks: CrmTask[] = [
  {
    id: 't-1',
    title: 'Request updated Experian report',
    status: 'open',
    priority: 'high',
    dueAt: '2026-07-23T17:00:00Z',
    assigneeName: 'Riley Quinn',
    relatedType: 'borrower',
    relatedName: 'Alex Rivera',
    relatedId: 'b-1',
    createdAt: '2026-07-20T12:00:00Z',
  },
  {
    id: 't-2',
    title: 'Send Partner Kit to Oak & Pine',
    status: 'in_progress',
    priority: 'normal',
    dueAt: '2026-07-24T17:00:00Z',
    assigneeName: 'Jordan Hale',
    relatedType: 'partner',
    relatedName: 'Oak & Pine Brokers',
    relatedId: 'p-oak',
    createdAt: '2026-07-19T09:00:00Z',
  },
  {
    id: 't-3',
    title: 'Confirm underwriting package for Frankie Cole',
    status: 'open',
    priority: 'urgent',
    dueAt: '2026-07-22T20:00:00Z',
    assigneeName: 'Morgan Ellis',
    relatedType: 'borrower',
    relatedName: 'Frankie Cole',
    relatedId: 'b-6',
    createdAt: '2026-07-21T15:00:00Z',
  },
  {
    id: 't-4',
    title: 'Weekly Summit Realty sync',
    status: 'open',
    priority: 'normal',
    dueAt: '2026-07-25T15:00:00Z',
    assigneeName: 'Casey Brooks',
    relatedType: 'realtor',
    relatedName: 'Pat Okonkwo',
    relatedId: 'r-pat',
    createdAt: '2026-07-18T11:00:00Z',
  },
  {
    id: 't-5',
    title: 'Close declined referral — incomplete docs',
    status: 'blocked',
    priority: 'low',
    dueAt: '2026-07-26T17:00:00Z',
    assigneeName: 'Riley Quinn',
    relatedType: 'referral',
    relatedName: 'Ellis Park',
    relatedId: 'ref-5',
    createdAt: '2026-07-17T14:00:00Z',
  },
];

export const workflowSteps: WorkflowStep[] = [
  {
    id: 'w-lead',
    name: 'Capture lead',
    stage: 'lead',
    slaDays: 1,
    ownerRole: 'Partner Manager',
    automations: 2,
    description: 'Log source, consent, and primary partner attribution.',
  },
  {
    id: 'w-qual',
    name: 'Qualify intent',
    stage: 'qualified',
    slaDays: 3,
    ownerRole: 'Loan Officer',
    automations: 1,
    description: 'Confirm loan goal, timeline, and partner handoff readiness.',
  },
  {
    id: 'w-ref',
    name: 'Accept referral',
    stage: 'referred',
    slaDays: 1,
    ownerRole: 'Ops Coordinator',
    automations: 3,
    description: 'Create borrower record and kick off intake checklist.',
  },
  {
    id: 'w-intake',
    name: 'Complete intake',
    stage: 'intake',
    slaDays: 5,
    ownerRole: 'Ops Coordinator',
    automations: 2,
    description: 'Tri-bureau docs, identity, and portal provisioning.',
  },
  {
    id: 'w-repair',
    name: 'Credit repair cycle',
    stage: 'in_repair',
    slaDays: 30,
    ownerRole: 'Case Manager (platform)',
    automations: 4,
    description: 'Staff-mediated dispute work; CRM tracks advisory progress only.',
  },
  {
    id: 'w-ready',
    name: 'Mortgage-ready package',
    stage: 'mortgage_ready',
    slaDays: 7,
    ownerRole: 'Loan Officer',
    automations: 2,
    description: 'Package readiness export for lender credit review—not a funding decision.',
  },
];

export const automations: AutomationRule[] = [
  {
    id: 'a-1',
    name: 'New referral → intake task',
    enabled: true,
    trigger: 'referral_created',
    action: 'Create high-priority intake task for Ops',
    channel: 'task',
    lastFiredAt: '2026-07-21T10:12:00Z',
    fireCount: 126,
    description: 'When a referral is accepted, enqueue document + portal setup tasks.',
  },
  {
    id: 'a-2',
    name: 'Stage enter near_ready → LO email',
    enabled: true,
    trigger: 'stage_enter',
    action: 'Email assigned LO with readiness summary link',
    channel: 'email',
    lastFiredAt: '2026-07-22T08:40:00Z',
    fireCount: 54,
    description: 'Advisory alert only; no underwriting commitment language.',
  },
  {
    id: 'a-3',
    name: 'Overdue task → SMS to assignee',
    enabled: true,
    trigger: 'task_overdue',
    action: 'SMS reminder to task assignee',
    channel: 'sms',
    lastFiredAt: '2026-07-20T19:00:00Z',
    fireCount: 89,
    description: 'Quiet hours respected via notifications SMS policy.',
  },
  {
    id: 'a-4',
    name: 'Score band → partner notification',
    enabled: false,
    trigger: 'score_band_change',
    action: 'In-app notification to partner owner',
    channel: 'notification',
    lastFiredAt: '2026-07-10T14:00:00Z',
    fireCount: 31,
    description: 'Disabled pending partner preference review.',
  },
  {
    id: 'a-5',
    name: 'Document uploaded → review task',
    enabled: true,
    trigger: 'document_uploaded',
    action: 'Create document review task',
    channel: 'task',
    lastFiredAt: '2026-07-22T07:55:00Z',
    fireCount: 210,
    description: 'Routes to Ops for classification before readiness refresh.',
  },
];

export const smsMessages: SmsMessage[] = [
  {
    id: 'sms-1',
    toName: 'Alex Rivera',
    toPhone: '(404) 555-1001',
    body: 'Reminder: please upload your latest Experian PDF in the borrower portal.',
    status: 'delivered',
    sentAt: '2026-07-21T15:30:00Z',
    direction: 'outbound',
    relatedBorrower: 'Alex Rivera',
  },
  {
    id: 'sms-2',
    toName: 'Pat Okonkwo',
    toPhone: '(770) 555-0198',
    body: 'Blake Nguyen moved to Near ready — advisory update only.',
    status: 'delivered',
    sentAt: '2026-07-22T08:45:00Z',
    direction: 'outbound',
    relatedBorrower: 'Blake Nguyen',
  },
  {
    id: 'sms-3',
    toName: 'Blake Nguyen',
    toPhone: '(770) 555-1002',
    body: 'Got it — portal upload completed.',
    status: 'replied',
    sentAt: '2026-07-22T09:02:00Z',
    direction: 'inbound',
    relatedBorrower: 'Blake Nguyen',
  },
  {
    id: 'sms-4',
    toName: 'Devon Shah',
    toPhone: '(404) 555-1004',
    body: 'Welcome to Lending Readiness Partners. Your portal invite is on the way.',
    status: 'queued',
    sentAt: '2026-07-22T12:00:00Z',
    direction: 'outbound',
    relatedBorrower: 'Devon Shah',
  },
];

export const emailMessages: EmailMessage[] = [
  {
    id: 'em-1',
    toName: 'Dana Whitfield',
    toEmail: 'dana@harborhome.demo',
    subject: 'Weekly readiness digest — Harbor Home',
    preview: '3 borrowers near ready, 1 mortgage-ready package attached…',
    status: 'opened',
    sentAt: '2026-07-21T13:00:00Z',
    direction: 'outbound',
    relatedBorrower: null,
  },
  {
    id: 'em-2',
    toName: 'Cameron Brooks',
    toEmail: 'cameron.brooks@example.com',
    subject: 'Your mortgage-ready summary is available',
    preview: 'Advisory readiness package for credit review — not a loan decision…',
    status: 'delivered',
    sentAt: '2026-07-21T16:20:00Z',
    direction: 'outbound',
    relatedBorrower: 'Cameron Brooks',
  },
  {
    id: 'em-3',
    toName: 'Taylor Sims',
    toEmail: 'taylor@oakpine.demo',
    subject: 'Partner Kit + stage glossary',
    preview: 'Materials for standardizing BD conversations…',
    status: 'sent',
    sentAt: '2026-07-19T10:15:00Z',
    direction: 'outbound',
    relatedBorrower: null,
  },
  {
    id: 'em-4',
    toName: 'Ops Desk',
    toEmail: 'ops@lrp.crm',
    subject: 'Re: Frankie Cole underwriting docs',
    preview: 'Lender requested updated VOE — please confirm…',
    status: 'replied',
    sentAt: '2026-07-22T09:40:00Z',
    direction: 'inbound',
    relatedBorrower: 'Frankie Cole',
  },
];

export const referrals: ReferralRecord[] = [
  {
    id: 'ref-1',
    borrowerName: 'Alex Rivera',
    borrowerEmail: 'alex.rivera@example.com',
    sourceType: 'lender',
    sourceName: 'Dana Whitfield / Harbor Home',
    loName: 'Morgan Ellis',
    status: 'in_progress',
    referredAt: '2026-06-02T14:00:00Z',
    attributedPartnerId: 'p-harbor',
    borrowerId: 'b-1',
    notes: 'Target close Q4.',
    conversionValue: 425000,
  },
  {
    id: 'ref-2',
    borrowerName: 'Blake Nguyen',
    borrowerEmail: 'blake.nguyen@example.com',
    sourceType: 'realtor',
    sourceName: 'Nina Patel / Summit',
    loName: 'Morgan Ellis',
    status: 'in_progress',
    referredAt: '2026-06-18T11:30:00Z',
    attributedPartnerId: 'p-summit',
    borrowerId: 'b-2',
    notes: 'FHA path; realtor wants weekly SMS.',
    conversionValue: 310000,
  },
  {
    id: 'ref-3',
    borrowerName: 'Harper Diaz',
    borrowerEmail: 'harper.diaz@example.com',
    sourceType: 'partner',
    sourceName: 'Crestline Credit Ops',
    loName: 'Jordan Hale',
    status: 'new',
    referredAt: '2026-07-21T09:00:00Z',
    attributedPartnerId: 'p-crest',
    borrowerId: null,
    notes: 'Awaiting acceptance.',
    conversionValue: null,
  },
  {
    id: 'ref-4',
    borrowerName: 'Cameron Brooks',
    borrowerEmail: 'cameron.brooks@example.com',
    sourceType: 'lender',
    sourceName: 'Dana Whitfield / Harbor Home',
    loName: 'Morgan Ellis',
    status: 'completed',
    referredAt: '2026-04-10T10:00:00Z',
    attributedPartnerId: 'p-harbor',
    borrowerId: 'b-3',
    notes: 'Mortgage-ready package delivered.',
    conversionValue: 280000,
  },
  {
    id: 'ref-5',
    borrowerName: 'Ellis Park',
    borrowerEmail: 'ellis.park@example.com',
    sourceType: 'web',
    sourceName: 'lrp.web / contact',
    loName: 'Morgan Ellis',
    status: 'declined',
    referredAt: '2026-05-22T16:00:00Z',
    attributedPartnerId: 'p-river',
    borrowerId: 'b-5',
    notes: 'Channel paused; incomplete docs.',
    conversionValue: null,
  },
];

export const calendarEvents: CalendarEvent[] = [
  {
    id: 'cal-1',
    title: 'Harbor Home weekly sync',
    startsAt: '2026-07-24T15:00:00Z',
    endsAt: '2026-07-24T15:30:00Z',
    type: 'meeting',
    relatedName: 'Harbor Home Mortgage',
    ownerName: 'Jordan Hale',
    location: 'Zoom',
  },
  {
    id: 'cal-2',
    title: 'Intake call — Devon Shah',
    startsAt: '2026-07-23T18:00:00Z',
    endsAt: '2026-07-23T18:30:00Z',
    type: 'call',
    relatedName: 'Devon Shah',
    ownerName: 'Riley Quinn',
    location: null,
  },
  {
    id: 'cal-3',
    title: 'Readiness package due — Cameron Brooks',
    startsAt: '2026-07-28T16:00:00Z',
    endsAt: '2026-07-28T16:00:00Z',
    type: 'deadline',
    relatedName: 'Cameron Brooks',
    ownerName: 'Morgan Ellis',
    location: null,
  },
  {
    id: 'cal-4',
    title: 'Summit Realty follow-up',
    startsAt: '2026-07-25T14:00:00Z',
    endsAt: '2026-07-25T14:45:00Z',
    type: 'follow_up',
    relatedName: 'Pat Okonkwo',
    ownerName: 'Casey Brooks',
    location: 'Alpharetta office',
  },
  {
    id: 'cal-5',
    title: 'Ops pipeline review',
    startsAt: '2026-07-22T20:00:00Z',
    endsAt: '2026-07-22T21:00:00Z',
    type: 'review',
    relatedName: 'Internal',
    ownerName: 'Avery Chen',
    location: 'HQ',
  },
];

export const documents: CrmDocument[] = [
  {
    id: 'd-1',
    name: 'Alex_Rivera_Experian.pdf',
    category: 'Credit report',
    relatedType: 'borrower',
    relatedName: 'Alex Rivera',
    status: 'in_review',
    uploadedAt: '2026-07-20T11:00:00Z',
    sizeLabel: '1.2 MB',
  },
  {
    id: 'd-2',
    name: 'Cameron_Brooks_Readiness_Pack.pdf',
    category: 'Readiness export',
    relatedType: 'borrower',
    relatedName: 'Cameron Brooks',
    status: 'verified',
    uploadedAt: '2026-07-21T16:05:00Z',
    sizeLabel: '840 KB',
  },
  {
    id: 'd-3',
    name: 'Harbor_Partner_Agreement.pdf',
    category: 'Partner agreement',
    relatedType: 'partner',
    relatedName: 'Harbor Home Mortgage',
    status: 'verified',
    uploadedAt: '2026-03-01T10:00:00Z',
    sizeLabel: '420 KB',
  },
  {
    id: 'd-4',
    name: 'Devon_Shah_Drivers_License.pdf',
    category: 'Identity',
    relatedType: 'borrower',
    relatedName: 'Devon Shah',
    status: 'pending',
    uploadedAt: '2026-07-18T14:20:00Z',
    sizeLabel: '310 KB',
  },
  {
    id: 'd-5',
    name: 'Referral_Harper_Diaz_intake.zip',
    category: 'Referral packet',
    relatedType: 'referral',
    relatedName: 'Harper Diaz',
    status: 'in_review',
    uploadedAt: '2026-07-21T09:10:00Z',
    sizeLabel: '2.4 MB',
  },
];

export const notes: CrmNote[] = [
  {
    id: 'n-1',
    body: 'Dana prefers readiness digests on Mondays before 10am ET. Avoid guarantee language in partner emails.',
    authorName: 'Jordan Hale',
    createdAt: '2026-07-14T13:00:00Z',
    pinned: true,
    relatedType: 'partner',
    relatedName: 'Harbor Home Mortgage',
    relatedId: 'p-harbor',
  },
  {
    id: 'n-2',
    body: 'Collection paydown plan agreed verbally; waiting on portal upload of settlement letter.',
    authorName: 'Riley Quinn',
    createdAt: '2026-07-21T11:20:00Z',
    pinned: false,
    relatedType: 'borrower',
    relatedName: 'Alex Rivera',
    relatedId: 'b-1',
  },
  {
    id: 'n-3',
    body: 'Nina asked for SMS when score crosses Near ready — automation a-2 covers LO email; SMS optional.',
    authorName: 'Casey Brooks',
    createdAt: '2026-07-19T16:40:00Z',
    pinned: false,
    relatedType: 'realtor',
    relatedName: 'Nina Patel',
    relatedId: 'r-nina',
  },
  {
    id: 'n-4',
    body: 'Internal: Riverbend paused — do not accept new referrals until compliance clears SLA.',
    authorName: 'Avery Chen',
    createdAt: '2026-06-28T17:00:00Z',
    pinned: true,
    relatedType: 'internal',
    relatedName: 'Compliance hold',
    relatedId: null,
  },
];

export const reporting: CrmReportingSnapshot = {
  periodLabel: 'Jul 2026 (MTD)',
  metrics: [
    { label: 'New referrals', value: '24', delta: '+18% vs prior', tone: 'up' },
    { label: 'Accepted', value: '19', delta: '+12%', tone: 'up' },
    { label: 'Mortgage ready', value: '7', delta: '+2', tone: 'up' },
    { label: 'Funded (attrib.)', value: '4', delta: 'flat', tone: 'flat' },
    { label: 'Avg days to near ready', value: '41', delta: '-3 days', tone: 'up' },
    { label: 'Pull-through', value: '62%', delta: '+4 pts', tone: 'up' },
  ],
  funnel: [
    { stage: 'lead', count: 12 },
    { stage: 'qualified', count: 9 },
    { stage: 'referred', count: 8 },
    { stage: 'intake', count: 6 },
    { stage: 'in_repair', count: 14 },
    { stage: 'near_ready', count: 5 },
    { stage: 'mortgage_ready', count: 3 },
    { stage: 'in_underwriting', count: 2 },
    { stage: 'funded', count: 4 },
  ],
  referralBySource: [
    { source: 'Lender', count: 11, converted: 7 },
    { source: 'Realtor', count: 8, converted: 5 },
    { source: 'Partner/operator', count: 3, converted: 2 },
    { source: 'Web/direct', count: 2, converted: 0 },
  ],
  partnerLeaderboard: [
    { partner: 'Harbor Home Mortgage', referrals: 18, funded: 42 },
    { partner: 'Summit Realty Group', referrals: 11, funded: 19 },
    { partner: 'Crestline Credit Ops', referrals: 7, funded: 28 },
  ],
};

export const architectureNotes = {
  edition: 'Lending Readiness Partners CRM (edition on shared Verdin platform)',
  mapsTo: {
    borrowers: 'Clients + Cases (apps/api clients/cases)',
    tasks: 'Tasks module',
    documents: 'Documents module',
    smsEmail: 'Notifications SMS/email delivery',
    messaging: 'Case messaging / portal threads',
    reportingOps: 'Reporting Center (ops) — CRM funnel is partner edition overlay',
    partnersReferrals: 'Planned ENABLE_MORTGAGE_PARTNER APIs (v29+)',
  },
  deferred: [
    'Live bureau pulls / unsupervised dispute filing',
    'Underwriting or funding guarantees',
    'Cross-tenant marketplaces',
  ],
};
