import type { CrmPermission, CrmRole, RoleDefinition } from '@/lib/crm/types';

const ALL: CrmPermission[] = [
  'dashboard.view',
  'partners.view',
  'partners.manage',
  'borrowers.view',
  'borrowers.manage',
  'lenders.view',
  'lenders.manage',
  'realtors.view',
  'realtors.manage',
  'tasks.view',
  'tasks.manage',
  'workflow.view',
  'workflow.manage',
  'pipeline.view',
  'pipeline.manage',
  'automations.view',
  'automations.manage',
  'sms.view',
  'sms.send',
  'email.view',
  'email.send',
  'reporting.view',
  'reporting.export',
  'referrals.view',
  'referrals.manage',
  'calendar.view',
  'calendar.manage',
  'documents.view',
  'documents.manage',
  'notes.view',
  'notes.manage',
  'admin.manage',
  'permissions.manage',
];

export const ROLE_DEFINITIONS: RoleDefinition[] = [
  {
    role: 'crm_admin',
    label: 'CRM Admin',
    description: 'Full CRM control including automations, admin, and role policy.',
    permissions: ALL,
  },
  {
    role: 'partner_manager',
    label: 'Partner Manager',
    description: 'Owns partner relationships, referrals, and channel reporting.',
    permissions: [
      'dashboard.view',
      'partners.view',
      'partners.manage',
      'borrowers.view',
      'lenders.view',
      'lenders.manage',
      'realtors.view',
      'realtors.manage',
      'tasks.view',
      'tasks.manage',
      'workflow.view',
      'pipeline.view',
      'automations.view',
      'sms.view',
      'sms.send',
      'email.view',
      'email.send',
      'reporting.view',
      'reporting.export',
      'referrals.view',
      'referrals.manage',
      'calendar.view',
      'calendar.manage',
      'documents.view',
      'notes.view',
      'notes.manage',
    ],
  },
  {
    role: 'loan_officer',
    label: 'Loan Officer',
    description: 'Borrower pipeline, tasks, messaging, and referral follow-up.',
    permissions: [
      'dashboard.view',
      'partners.view',
      'borrowers.view',
      'borrowers.manage',
      'lenders.view',
      'realtors.view',
      'tasks.view',
      'tasks.manage',
      'workflow.view',
      'pipeline.view',
      'pipeline.manage',
      'sms.view',
      'sms.send',
      'email.view',
      'email.send',
      'reporting.view',
      'referrals.view',
      'referrals.manage',
      'calendar.view',
      'calendar.manage',
      'documents.view',
      'documents.manage',
      'notes.view',
      'notes.manage',
    ],
  },
  {
    role: 'realtor_liaison',
    label: 'Realtor Liaison',
    description: 'Realtor channel, calendar coordination, and light borrower visibility.',
    permissions: [
      'dashboard.view',
      'partners.view',
      'borrowers.view',
      'realtors.view',
      'realtors.manage',
      'tasks.view',
      'tasks.manage',
      'pipeline.view',
      'sms.view',
      'sms.send',
      'email.view',
      'email.send',
      'referrals.view',
      'referrals.manage',
      'calendar.view',
      'calendar.manage',
      'documents.view',
      'notes.view',
      'notes.manage',
    ],
  },
  {
    role: 'ops_coordinator',
    label: 'Ops Coordinator',
    description: 'Workflow, tasks, documents, and stage operations.',
    permissions: [
      'dashboard.view',
      'borrowers.view',
      'borrowers.manage',
      'tasks.view',
      'tasks.manage',
      'workflow.view',
      'workflow.manage',
      'pipeline.view',
      'pipeline.manage',
      'automations.view',
      'sms.view',
      'email.view',
      'reporting.view',
      'referrals.view',
      'calendar.view',
      'documents.view',
      'documents.manage',
      'notes.view',
      'notes.manage',
    ],
  },
  {
    role: 'read_only',
    label: 'Read Only',
    description: 'Visibility across CRM without mutation or outbound messaging.',
    permissions: [
      'dashboard.view',
      'partners.view',
      'borrowers.view',
      'lenders.view',
      'realtors.view',
      'tasks.view',
      'workflow.view',
      'pipeline.view',
      'automations.view',
      'sms.view',
      'email.view',
      'reporting.view',
      'referrals.view',
      'calendar.view',
      'documents.view',
      'notes.view',
    ],
  },
];

const byRole = Object.fromEntries(
  ROLE_DEFINITIONS.map((def) => [def.role, new Set(def.permissions)]),
) as Record<CrmRole, Set<CrmPermission>>;

export function roleHasPermission(role: CrmRole, permission: CrmPermission): boolean {
  return byRole[role]?.has(permission) ?? false;
}

export function permissionsForRole(role: CrmRole): CrmPermission[] {
  return ROLE_DEFINITIONS.find((d) => d.role === role)?.permissions ?? [];
}

export const PERMISSION_LABELS: Record<CrmPermission, string> = {
  'dashboard.view': 'View dashboard',
  'partners.view': 'View partners',
  'partners.manage': 'Manage partners',
  'borrowers.view': 'View borrowers',
  'borrowers.manage': 'Manage borrowers',
  'lenders.view': 'View lenders',
  'lenders.manage': 'Manage lenders',
  'realtors.view': 'View realtors',
  'realtors.manage': 'Manage realtors',
  'tasks.view': 'View tasks',
  'tasks.manage': 'Manage tasks',
  'workflow.view': 'View workflow',
  'workflow.manage': 'Manage workflow',
  'pipeline.view': 'View pipeline',
  'pipeline.manage': 'Manage pipeline',
  'automations.view': 'View automations',
  'automations.manage': 'Manage automations',
  'sms.view': 'View SMS',
  'sms.send': 'Send SMS',
  'email.view': 'View email',
  'email.send': 'Send email',
  'reporting.view': 'View reporting',
  'reporting.export': 'Export reporting',
  'referrals.view': 'View referrals',
  'referrals.manage': 'Manage referrals',
  'calendar.view': 'View calendar',
  'calendar.manage': 'Manage calendar',
  'documents.view': 'View documents',
  'documents.manage': 'Manage documents',
  'notes.view': 'View notes',
  'notes.manage': 'Manage notes',
  'admin.manage': 'Admin panel',
  'permissions.manage': 'Manage role permissions',
};
