import type {
  AnalyticsSnapshot,
  Borrower,
  LenderDocument,
  LenderNotification,
  LenderThread,
  LenderUser,
  MonthlyReport,
  OrgAdminSettings,
  PipelineCard,
  ReadinessReport,
  Referral,
} from '@/lib/lender/types';

export const DEMO_USERS: Array<LenderUser & { password: string }> = [
  {
    id: 'lu-admin',
    email: 'admin@lrp.lender',
    password: 'changeme123',
    displayName: 'Morgan Ellis',
    role: 'lender_admin',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Home Mortgage',
    title: 'Partner Administrator',
  },
  {
    id: 'lu-lo',
    email: 'lo@lrp.lender',
    password: 'changeme123',
    displayName: 'Sam Okonkwo',
    role: 'loan_officer',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Home Mortgage',
    title: 'Senior Loan Officer',
  },
  {
    id: 'lu-ops',
    email: 'ops@lrp.lender',
    password: 'changeme123',
    displayName: 'Riley Chen',
    role: 'credit_ops',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Home Mortgage',
    title: 'Credit Operations Lead',
  },
  {
    id: 'lu-uw',
    email: 'uw@lrp.lender',
    password: 'changeme123',
    displayName: 'Jordan Blake',
    role: 'underwriter_view',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Home Mortgage',
    title: 'Credit Risk Analyst',
  },
];

export const orgSettings: OrgAdminSettings = {
  organizationName: 'Harbor Home Mortgage',
  partnerCode: 'HHM-LRP-029',
  brandingPrimary: '#00133E',
  readinessExportEnabled: true,
  notifyOnStageChange: true,
  notifyOnReady: true,
  defaultLoId: 'lu-lo',
  retentionDays: 365,
};

const disclaimer =
  'Advisory readiness composite for partner handoff—not a credit score, underwriting decision, or funding guarantee. Sensitive dispute steps remain staff-mediated on the CRO platform.';

export const borrowers: Borrower[] = [
  {
    id: 'br-1001',
    displayName: 'Alex Rivera',
    email: 'alex.rivera@example.com',
    phone: '(555) 210-8841',
    loName: 'Sam Okonkwo',
    stage: 'near_ready',
    readinessScore: 78,
    readinessBand: 'Near Ready',
    estimatedReadyDate: '2026-08-18',
    progressPct: 72,
    lastActivityAt: '2026-07-21T14:20:00Z',
    referralId: 'ref-01',
    blockers: ['Revolving utilization above 35%', 'Medical collection under review'],
    loanAmountTarget: 425000,
    propertyState: 'NC',
    milestones: [
      { id: 'm1', label: 'Referral accepted', complete: true, completedAt: '2026-06-12' },
      {
        id: 'm2',
        label: 'Baseline readiness established',
        complete: true,
        completedAt: '2026-06-20',
      },
      {
        id: 'm3',
        label: 'High-impact blockers identified',
        complete: true,
        completedAt: '2026-06-28',
      },
      { id: 'm4', label: 'Utilization remediation', complete: false, completedAt: null },
      { id: 'm5', label: 'Collection package mediated', complete: false, completedAt: null },
      { id: 'm6', label: 'Lending-ready export', complete: false, completedAt: null },
    ],
  },
  {
    id: 'br-1002',
    displayName: 'Casey Nguyen',
    email: 'casey.nguyen@example.com',
    phone: '(555) 441-2290',
    loName: 'Sam Okonkwo',
    stage: 'in_repair',
    readinessScore: 61,
    readinessBand: 'Building',
    estimatedReadyDate: '2026-09-12',
    progressPct: 48,
    lastActivityAt: '2026-07-20T11:05:00Z',
    referralId: 'ref-02',
    blockers: ['Evidence needed on charge-off', 'Income docs incomplete'],
    loanAmountTarget: 310000,
    propertyState: 'SC',
    milestones: [
      { id: 'm1', label: 'Referral accepted', complete: true, completedAt: '2026-06-18' },
      {
        id: 'm2',
        label: 'Baseline readiness established',
        complete: true,
        completedAt: '2026-06-25',
      },
      {
        id: 'm3',
        label: 'High-impact blockers identified',
        complete: true,
        completedAt: '2026-07-02',
      },
      { id: 'm4', label: 'Evidence collection', complete: false, completedAt: null },
      { id: 'm5', label: 'Utilization remediation', complete: false, completedAt: null },
      { id: 'm6', label: 'Lending-ready export', complete: false, completedAt: null },
    ],
  },
  {
    id: 'br-1003',
    displayName: 'Taylor Brooks',
    email: 'taylor.brooks@example.com',
    phone: '(555) 903-1172',
    loName: 'Sam Okonkwo',
    stage: 'mortgage_ready',
    readinessScore: 88,
    readinessBand: 'Lending Ready',
    estimatedReadyDate: '2026-07-28',
    progressPct: 94,
    lastActivityAt: '2026-07-22T09:40:00Z',
    referralId: 'ref-03',
    blockers: [],
    loanAmountTarget: 540000,
    propertyState: 'VA',
    milestones: [
      { id: 'm1', label: 'Referral accepted', complete: true, completedAt: '2026-05-04' },
      {
        id: 'm2',
        label: 'Baseline readiness established',
        complete: true,
        completedAt: '2026-05-12',
      },
      {
        id: 'm3',
        label: 'High-impact blockers identified',
        complete: true,
        completedAt: '2026-05-20',
      },
      { id: 'm4', label: 'Utilization remediation', complete: true, completedAt: '2026-06-30' },
      { id: 'm5', label: 'Collection package mediated', complete: true, completedAt: '2026-07-10' },
      { id: 'm6', label: 'Lending-ready export', complete: true, completedAt: '2026-07-21' },
    ],
  },
  {
    id: 'br-1004',
    displayName: 'Jamie Ortiz',
    email: 'jamie.ortiz@example.com',
    phone: '(555) 772-4401',
    loName: 'Sam Okonkwo',
    stage: 'in_underwriting',
    readinessScore: 91,
    readinessBand: 'Lending Ready',
    estimatedReadyDate: '2026-07-15',
    progressPct: 97,
    lastActivityAt: '2026-07-21T16:00:00Z',
    referralId: 'ref-04',
    blockers: [],
    loanAmountTarget: 389000,
    propertyState: 'NC',
    milestones: [
      { id: 'm1', label: 'Referral accepted', complete: true, completedAt: '2026-04-22' },
      {
        id: 'm2',
        label: 'Baseline readiness established',
        complete: true,
        completedAt: '2026-04-30',
      },
      {
        id: 'm3',
        label: 'High-impact blockers identified',
        complete: true,
        completedAt: '2026-05-08',
      },
      { id: 'm4', label: 'Utilization remediation', complete: true, completedAt: '2026-06-01' },
      { id: 'm5', label: 'Collection package mediated', complete: true, completedAt: '2026-06-20' },
      { id: 'm6', label: 'Lending-ready export', complete: true, completedAt: '2026-07-08' },
    ],
  },
  {
    id: 'br-1005',
    displayName: 'Morgan Patel',
    email: 'morgan.patel@example.com',
    phone: '(555) 318-6650',
    loName: 'Sam Okonkwo',
    stage: 'intake',
    readinessScore: 44,
    readinessBand: 'Early Stage',
    estimatedReadyDate: '2026-10-05',
    progressPct: 22,
    lastActivityAt: '2026-07-19T10:15:00Z',
    referralId: 'ref-05',
    blockers: ['Identity docs pending', 'No baseline credit import yet'],
    loanAmountTarget: 275000,
    propertyState: 'GA',
    milestones: [
      { id: 'm1', label: 'Referral accepted', complete: true, completedAt: '2026-07-14' },
      { id: 'm2', label: 'Baseline readiness established', complete: false, completedAt: null },
      { id: 'm3', label: 'High-impact blockers identified', complete: false, completedAt: null },
      { id: 'm4', label: 'Utilization remediation', complete: false, completedAt: null },
      { id: 'm5', label: 'Collection package mediated', complete: false, completedAt: null },
      { id: 'm6', label: 'Lending-ready export', complete: false, completedAt: null },
    ],
  },
  {
    id: 'br-1006',
    displayName: 'Reese Kim',
    email: 'reese.kim@example.com',
    phone: '(555) 620-9912',
    loName: 'Sam Okonkwo',
    stage: 'referred',
    readinessScore: 0,
    readinessBand: 'Awaiting intake',
    estimatedReadyDate: null,
    progressPct: 8,
    lastActivityAt: '2026-07-22T08:00:00Z',
    referralId: 'ref-06',
    blockers: ['Awaiting borrower consent'],
    loanAmountTarget: 360000,
    propertyState: 'NC',
    milestones: [
      { id: 'm1', label: 'Referral accepted', complete: false, completedAt: null },
      { id: 'm2', label: 'Baseline readiness established', complete: false, completedAt: null },
      { id: 'm3', label: 'High-impact blockers identified', complete: false, completedAt: null },
      { id: 'm4', label: 'Utilization remediation', complete: false, completedAt: null },
      { id: 'm5', label: 'Collection package mediated', complete: false, completedAt: null },
      { id: 'm6', label: 'Lending-ready export', complete: false, completedAt: null },
    ],
  },
];

export const referrals: Referral[] = [
  {
    id: 'ref-01',
    borrowerName: 'Alex Rivera',
    borrowerEmail: 'alex.rivera@example.com',
    source: 'Realtor — Coastal Group',
    loName: 'Sam Okonkwo',
    status: 'in_progress',
    referredAt: '2026-06-12',
    targetProduct: 'Conventional purchase',
    notes: 'Target close window Q3; utilization is primary lever.',
    borrowerId: 'br-1001',
  },
  {
    id: 'ref-02',
    borrowerName: 'Casey Nguyen',
    borrowerEmail: 'casey.nguyen@example.com',
    source: 'Branch LO',
    loName: 'Sam Okonkwo',
    status: 'in_progress',
    referredAt: '2026-06-18',
    targetProduct: 'FHA purchase',
    notes: 'Charge-off evidence requested from CRO.',
    borrowerId: 'br-1002',
  },
  {
    id: 'ref-03',
    borrowerName: 'Taylor Brooks',
    borrowerEmail: 'taylor.brooks@example.com',
    source: 'Realtor — Summit Realty',
    loName: 'Sam Okonkwo',
    status: 'completed',
    referredAt: '2026-05-04',
    targetProduct: 'Conventional purchase',
    notes: 'Ready for underwriting handoff.',
    borrowerId: 'br-1003',
  },
  {
    id: 'ref-04',
    borrowerName: 'Jamie Ortiz',
    borrowerEmail: 'jamie.ortiz@example.com',
    source: 'Partner bank referral',
    loName: 'Sam Okonkwo',
    status: 'completed',
    referredAt: '2026-04-22',
    targetProduct: 'VA purchase',
    notes: 'In underwriting with readiness packet attached.',
    borrowerId: 'br-1004',
  },
  {
    id: 'ref-05',
    borrowerName: 'Morgan Patel',
    borrowerEmail: 'morgan.patel@example.com',
    source: 'Website intake',
    loName: 'Sam Okonkwo',
    status: 'accepted',
    referredAt: '2026-07-14',
    targetProduct: 'Conventional purchase',
    notes: 'Awaiting identity docs.',
    borrowerId: 'br-1005',
  },
  {
    id: 'ref-06',
    borrowerName: 'Reese Kim',
    borrowerEmail: 'reese.kim@example.com',
    source: 'Realtor — Harbor Partners',
    loName: 'Sam Okonkwo',
    status: 'new',
    referredAt: '2026-07-22',
    targetProduct: 'Conventional purchase',
    notes: 'New referral — consent not yet signed.',
    borrowerId: 'br-1006',
  },
  {
    id: 'ref-07',
    borrowerName: 'Drew Alvarez',
    borrowerEmail: 'drew.alvarez@example.com',
    source: 'Realtor — Coastal Group',
    loName: 'Sam Okonkwo',
    status: 'declined',
    referredAt: '2026-07-01',
    targetProduct: 'Jumbo',
    notes: 'Borrower withdrew before intake.',
    borrowerId: null,
  },
];

export const readinessReports: ReadinessReport[] = borrowers
  .filter((b) => b.readinessScore > 0)
  .map((b) => ({
    id: `rr-${b.id}`,
    borrowerId: b.id,
    borrowerName: b.displayName,
    overall: b.readinessScore,
    band: b.readinessBand,
    generatedAt: b.lastActivityAt,
    estimatedReadyDate: b.estimatedReadyDate,
    dimensions: [
      { key: 'payment', label: 'Payment History', score: Math.min(100, b.readinessScore + 4) },
      {
        key: 'utilization',
        label: 'Credit Utilization',
        score: Math.max(20, b.readinessScore - 8),
      },
      {
        key: 'evidence',
        label: 'Evidence Completeness',
        score: Math.min(100, b.readinessScore + 2),
      },
      { key: 'dispute', label: 'Dispute Readiness', score: b.readinessScore },
      {
        key: 'public',
        label: 'Public Records / Collections',
        score: Math.max(25, b.readinessScore - b.blockers.length * 6),
      },
    ],
    blockers: b.blockers.map((title, i) => ({
      title,
      impact: i === 0 ? 'High' : 'Medium',
      action: 'Coordinate with CRO advisor for staff-mediated next step',
    })),
    disclaimer,
  }));

export const pipelineCards: PipelineCard[] = borrowers.map((b) => ({
  id: `pc-${b.id}`,
  borrowerId: b.id,
  borrowerName: b.displayName,
  stage: b.stage,
  readinessScore: b.readinessScore,
  estimatedReadyDate: b.estimatedReadyDate,
  loName: b.loName,
  daysInStage:
    b.stage === 'referred' ? 1 : b.stage === 'intake' ? 8 : b.stage === 'in_repair' ? 21 : 12,
}));

export const documents: LenderDocument[] = [
  {
    id: 'ld-1',
    borrowerId: 'br-1001',
    borrowerName: 'Alex Rivera',
    name: 'Government ID.pdf',
    category: 'Identity',
    status: 'verified',
    uploadedAt: '2026-07-08',
    sizeLabel: '1.2 MB',
  },
  {
    id: 'ld-2',
    borrowerId: 'br-1001',
    borrowerName: 'Alex Rivera',
    name: 'Pay stubs Jun–Jul.pdf',
    category: 'Income',
    status: 'in_review',
    uploadedAt: '2026-07-20',
    sizeLabel: '840 KB',
  },
  {
    id: 'ld-3',
    borrowerId: 'br-1002',
    borrowerName: 'Casey Nguyen',
    name: 'Charge-off statement.pdf',
    category: 'Disputes',
    status: 'pending',
    uploadedAt: '2026-07-18',
    sizeLabel: '620 KB',
  },
  {
    id: 'ld-4',
    borrowerId: 'br-1003',
    borrowerName: 'Taylor Brooks',
    name: 'Readiness export — Jul 21.pdf',
    category: 'Readiness',
    status: 'verified',
    uploadedAt: '2026-07-21',
    sizeLabel: '410 KB',
  },
  {
    id: 'ld-5',
    borrowerId: 'br-1004',
    borrowerName: 'Jamie Ortiz',
    name: 'Underwriting packet.zip',
    category: 'Readiness',
    status: 'verified',
    uploadedAt: '2026-07-08',
    sizeLabel: '3.4 MB',
  },
  {
    id: 'ld-6',
    borrowerId: 'br-1005',
    borrowerName: 'Morgan Patel',
    name: 'Proof of address.pdf',
    category: 'Identity',
    status: 'pending',
    uploadedAt: '2026-07-19',
    sizeLabel: '540 KB',
  },
];

export const threads: LenderThread[] = [
  {
    id: 'th-1',
    borrowerId: 'br-1001',
    borrowerName: 'Alex Rivera',
    subject: 'Utilization paydown plan',
    updatedAt: '2026-07-21T14:20:00Z',
    unread: 1,
    preview: 'CRO confirmed card 4821 paydown is tracking for next cycle.',
    messages: [
      {
        id: 'tm1',
        from: 'Alex Rivera (CRO)',
        body: "Paydown on card ending 4821 is scheduled. We'll recalculate readiness after the next import.",
        at: '2026-07-20T16:00:00Z',
        mine: false,
      },
      {
        id: 'tm2',
        from: 'Sam Okonkwo',
        body: 'Thanks — keep the realtor timeline soft until utilization holds under 30%.',
        at: '2026-07-20T18:12:00Z',
        mine: true,
      },
      {
        id: 'tm3',
        from: 'Alex Rivera (CRO)',
        body: 'CRO confirmed card 4821 paydown is tracking for next cycle.',
        at: '2026-07-21T14:20:00Z',
        mine: false,
      },
    ],
  },
  {
    id: 'th-2',
    borrowerId: 'br-1003',
    borrowerName: 'Taylor Brooks',
    subject: 'Ready for underwriting handoff',
    updatedAt: '2026-07-22T09:40:00Z',
    unread: 0,
    preview: 'Readiness export attached. No open high-impact blockers.',
    messages: [
      {
        id: 'tm4',
        from: 'Riley Chen',
        body: 'Readiness export attached. No open high-impact blockers.',
        at: '2026-07-22T09:40:00Z',
        mine: true,
      },
    ],
  },
  {
    id: 'th-3',
    borrowerId: 'br-1002',
    borrowerName: 'Casey Nguyen',
    subject: 'Evidence request — charge-off',
    updatedAt: '2026-07-20T11:05:00Z',
    unread: 2,
    preview: 'Need borrower confirmation on account number ending 2291.',
    messages: [
      {
        id: 'tm5',
        from: 'CRO Desk',
        body: 'Need borrower confirmation on account number ending 2291 before mediated package prep.',
        at: '2026-07-20T11:05:00Z',
        mine: false,
      },
    ],
  },
];

export const analytics: AnalyticsSnapshot = {
  periodLabel: 'Trailing 90 days',
  referralsAccepted: 18,
  avgDaysToNearReady: 41,
  mortgageReadyCount: 7,
  fundedCount: 4,
  pullThroughRate: 0.62,
  stageDistribution: [
    { stage: 'referred', count: 1 },
    { stage: 'intake', count: 1 },
    { stage: 'in_repair', count: 1 },
    { stage: 'near_ready', count: 1 },
    { stage: 'mortgage_ready', count: 1 },
    { stage: 'in_underwriting', count: 1 },
    { stage: 'funded', count: 0 },
    { stage: 'declined', count: 0 },
    { stage: 'withdrawn', count: 0 },
  ],
  readinessBands: [
    { band: 'Lending Ready', count: 2 },
    { band: 'Near Ready', count: 1 },
    { band: 'Building', count: 1 },
    { band: 'Early Stage', count: 1 },
    { band: 'Awaiting intake', count: 1 },
  ],
  monthlyTrend: [
    { month: '2026-02', referred: 4, ready: 1, funded: 0 },
    { month: '2026-03', referred: 5, ready: 2, funded: 1 },
    { month: '2026-04', referred: 6, ready: 2, funded: 1 },
    { month: '2026-05', referred: 7, ready: 3, funded: 1 },
    { month: '2026-06', referred: 8, ready: 3, funded: 1 },
    { month: '2026-07', referred: 6, ready: 2, funded: 0 },
  ],
};

export const monthlyReports: MonthlyReport[] = [
  {
    id: 'mr-2026-06',
    month: '2026-06',
    title: 'June partner readiness report',
    generatedAt: '2026-07-02T12:00:00Z',
    highlights: [
      'Pull-through improved 6 pts vs prior month on near-miss files.',
      'Average days to Near Ready held at 41 with utilization-focused remediation.',
      'Two readiness exports completed for underwriting handoff.',
    ],
    metrics: [
      { label: 'Referrals accepted', value: '8' },
      { label: 'Mortgage-ready', value: '3' },
      { label: 'Funded', value: '1' },
      { label: 'Avg days to near ready', value: '41' },
    ],
  },
  {
    id: 'mr-2026-05',
    month: '2026-05',
    title: 'May partner readiness report',
    generatedAt: '2026-06-03T12:00:00Z',
    highlights: [
      'Collection mediation cycle time improved after checklist seeding.',
      'No compliance exceptions on partner-scoped exports.',
    ],
    metrics: [
      { label: 'Referrals accepted', value: '7' },
      { label: 'Mortgage-ready', value: '3' },
      { label: 'Funded', value: '1' },
      { label: 'Avg days to near ready', value: '44' },
    ],
  },
];

export const notifications: LenderNotification[] = [
  {
    id: 'n1',
    title: 'Borrower entered Mortgage Ready',
    body: 'Taylor Brooks readiness export is available for underwriting handoff.',
    at: '2026-07-22T09:42:00Z',
    read: false,
    href: '/lender/borrowers/br-1003',
    severity: 'success',
  },
  {
    id: 'n2',
    title: 'New referral received',
    body: 'Reese Kim referred by Harbor Partners — consent pending.',
    at: '2026-07-22T08:05:00Z',
    read: false,
    href: '/lender/referrals',
    severity: 'info',
  },
  {
    id: 'n3',
    title: 'Evidence requested',
    body: 'Casey Nguyen charge-off confirmation needed from CRO desk.',
    at: '2026-07-20T11:10:00Z',
    read: false,
    href: '/lender/messages',
    severity: 'warn',
  },
  {
    id: 'n4',
    title: 'Monthly report ready',
    body: 'June partner readiness report is available to export.',
    at: '2026-07-02T12:05:00Z',
    read: true,
    href: '/lender/reports',
    severity: 'info',
  },
];

export function getBorrower(id: string): Borrower | undefined {
  return borrowers.find((b) => b.id === id);
}

export function getReadinessForBorrower(id: string): ReadinessReport | undefined {
  return readinessReports.find((r) => r.borrowerId === id);
}
