import { apiPath, request } from './http';

export {
  ApiClientError,
  ApiNotImplementedError,
  apiPath,
  configureApiClient,
  getAccessToken,
  getApiBaseUrl,
  notImplemented,
  request,
  setAccessToken,
  uploadRequest,
  type ApiClientConfig,
  type RequestOptions,
} from './http';

export {
  getCurrentUser,
  login,
  refreshToken,
  type LoginRequest,
  type RefreshTokenRequest,
  type TokenResponse,
  type User,
} from './auth';

export {
  getDashboard,
  type DashboardAccounts,
  type DashboardAlertItem,
  type DashboardAlerts,
  type DashboardAlertSeverity,
  type DashboardAlertType,
  type DashboardCases,
  type DashboardDocuments,
  type DashboardOperations,
  type DashboardOverview,
  type DashboardPerformance,
  type DashboardProcessing,
  type DashboardResponse,
  type DashboardTasks,
  type DashboardTimelineItem,
} from './dashboard';

export {
  getBureauPerformanceReporting,
  getCrossOrgBenchmarkAnalytics,
  getCrossOrgBenchmarkAnalyticsStatus,
  getEnterpriseReportingStatus,
  getMaterializedReportingStatus,
  getOperationsReporting,
  getPredictiveAnalyticsStatus,
  getPredictiveOutcomesReporting,
  getRevenueAnalyticsReporting,
  getTeamProductivityReporting,
  getUnredactedCrossOrgBenchmarkExportStatus,
  getLiveUnredactedBenchmarkBlobExportStatus,
  listMaterializedReportingRefreshRuns,
  listCrossOrgBenchmarkRuns,
  listUnredactedCrossOrgBenchmarkExportRuns,
  listLiveUnredactedBenchmarkBlobExportRuns,
  approveUnredactedCrossOrgBenchmarkExportRun,
  approveLiveUnredactedBenchmarkBlobExportRun,
  refreshCrossOrgBenchmarks,
  refreshMaterializedReportingViews,
  refreshPredictiveOutcomesReporting,
  submitUnredactedCrossOrgBenchmarkExport,
  submitLiveUnredactedBenchmarkBlobExport,
  type BureauPerformanceItem,
  type BureauPerformanceReporting,
  type BureauPerformanceReportingResponse,
  type ClientReportingMetrics,
  type CrossOrgBenchmarkAnalytics,
  type CrossOrgBenchmarkAnalyticsResponse,
  type CrossOrgBenchmarkAnalyticsStatus,
  type CrossOrgBenchmarkRefreshResponse,
  type CrossOrgBenchmarkRun,
  type UnredactedCrossOrgBenchmarkExportRun,
  type UnredactedCrossOrgBenchmarkExportRunResult,
  type UnredactedCrossOrgBenchmarkExportStatus,
  type UnredactedCrossOrgBenchmarkExportSubmitRequest,
  type LiveUnredactedBenchmarkBlobExportRun,
  type LiveUnredactedBenchmarkBlobExportRunResult,
  type LiveUnredactedBenchmarkBlobExportStatus,
  type LiveUnredactedBenchmarkBlobExportSubmitRequest,
  type EnterpriseReportingStatus,
  type MaterializedReportingStatus,
  type NotificationReportingMetrics,
  type OperationsReporting,
  type OperationsReportingResponse,
  type PredictiveAnalyticsStatus,
  type PredictiveOutcomeRefreshResult,
  type PredictiveOutcomeRefreshRun,
  type PredictiveOutcomes,
  type PredictiveOutcomesReportingResponse,
  type ReportingMvRefreshResult,
  type ReportingMvRefreshRun,
  type RevenueAnalytics,
  type RevenueAnalyticsReportingResponse,
  type TeamMemberProductivity,
  type TeamProductivityReporting,
  type TeamProductivityReportingResponse,
} from './reporting';

export {
  createCase,
  deleteCase,
  generateCaseLlmSummary,
  getCase,
  getCaseCreditReportDiscrepancies,
  getCaseMetro2Findings,
  getCaseFcraFindings,
  getCaseTradelineChronology,
  getCaseComplianceEvidenceLinks,
  getCaseLitigationStrength,
  getCaseDisputeStrategy,
  listCases,
  prepareCaseCreditReportDisputes,
  prepareCaseDisputeStrategyStage,
  downloadCaseDisputeMailPackets,
  downloadCaseDisputeReportExcerpts,
  uploadCaseIdentityDocument,
  updateCase,
  type BureauTradelineSnapshot,
  type Case,
  type CaseCreditReportDiscrepancies,
  type CaseLlmSummary,
  type CaseMetro2Findings,
  type CaseFcraFindings,
  type CaseTradelineChronology,
  type CaseComplianceEvidenceLinks,
  type CaseDisputeStrategy,
  type CaseLitigationStrength,
  type CreateCaseInput,
  type CrossBureauComparisonSummary,
  type CrossBureauDiscrepancy,
  type CrossBureauFieldDiff,
  type ListCasesParams,
  type PrepareCreditReportDisputesInput,
  type PrepareCreditReportDisputesResult,
  type PrepareDisputeStrategyStageInput,
  type PrepareDisputeStrategyStageResult,
  type PreparedCreditReportDisputeItem,
  type UpdateCaseInput,
} from './cases';

export {
  createClient,
  createClientContact,
  deleteClient,
  deleteClientContact,
  getClient,
  getClientContact,
  listClientContacts,
  listClients,
  updateClient,
  updateClientContact,
  uploadClientIdentityDocument,
  uploadClientProofOfAddressDocument,
  type Client,
  type ClientContact,
  type ClientStatus,
  type ContactRelationship,
  type CreateClientContactInput,
  type CreateClientInput,
  type ListClientContactsParams,
  type ListClientsParams,
  type UpdateClientContactInput,
  type UpdateClientInput,
} from './clients';

export {
  approveAgentExecutionStep,
  approveAgentArbitraryExecutionRun,
  approveAgentSupervisedLoopRun,
  approveAgentUnsupervisedLoopRun,
  approveAgentToolInvocationRequest,
  getAgentArbitraryExecutionStatus,
  getAgentExecutionStatus,
  getAgentExternalToolCallingStatus,
  getAgentObservabilityStatus,
  getAgentSupervisedLoopStatus,
  getAgentUnsupervisedLoopStatus,
  getLlmDisputeDraftAugmentStatus,
  getLlmStatus,
  listAgentArbitraryExecutionRuns,
  listAgentExecutionSteps,
  listAgentObservabilityRuns,
  listAgentSupervisedLoopRuns,
  listAgentUnsupervisedLoopRuns,
  listAgentToolInvocationRequests,
  runAgentObservabilityScaffold,
  startAgentArbitraryExecutionFromUnsupervisedRun,
  startAgentSupervisedLoopFromToolRequest,
  startAgentUnsupervisedLoopFromSupervisedRun,
  submitAgentExecutionStep,
  submitAgentToolInvocationRequest,
  type AgentArbitraryExecutionGateStatus,
  type AgentArbitraryExecutionRun,
  type AgentArbitraryExecutionRunResult,
  type AgentArbitraryExecutionStatus,
  type AgentArbitraryExecutionSubmitInput,
  type AgentExecutionStatus,
  type AgentExecutionStep,
  type AgentExecutionStepResult,
  type AgentExecutionStepStatus,
  type AgentExecutionStepSubmitInput,
  type AgentExternalToolCallingStatus,
  type AgentExternalToolKind,
  type AgentObservabilityKind,
  type AgentObservabilityRun,
  type AgentObservabilityRunInput,
  type AgentObservabilityRunResult,
  type AgentObservabilityRunStatus,
  type AgentObservabilityStatus,
  type AgentObservabilityTriggerSource,
  type AgentSupervisedLoopGateStatus,
  type AgentSupervisedLoopRun,
  type AgentSupervisedLoopRunResult,
  type AgentSupervisedLoopStatus,
  type AgentSupervisedLoopSubmitInput,
  type AgentUnsupervisedLoopGateStatus,
  type AgentUnsupervisedLoopRun,
  type AgentUnsupervisedLoopRunResult,
  type AgentUnsupervisedLoopStatus,
  type AgentUnsupervisedLoopSubmitInput,
  type AgentToolInvocationRequest,
  type AgentToolInvocationRequestResult,
  type AgentToolInvocationStatus,
  type AgentToolInvocationSubmitInput,
  type LlmGateStatus,
  type LlmDisputeDraftAugmentStatus,
} from './llm';

export {
  completeSsoEnrollment,
  confirmTotpEnrollment,
  disableTotpEnrollment,
  getEnterpriseIdentityStatus,
  getHrisBidirectionalSyncStatus,
  getHrisLifecycleSyncStatus,
  getIdpFederationStatus,
  getSamlAutomatedRotationStatus,
  getSamlCertificateRotationStatus,
  getBulkIdpProvisioningStatus,
  getHrisPasswordlessUiStatus,
  getMobilePasskeyReadinessStatus,
  getNativeMobilePasskeyClientStatus,
  getNativeMobileAppStoreDistributionStatus,
  getSamlPasswordlessEnrollmentStatus,
  getSamlFederationMetadataStatus,
  getScimProvisioningStatus,
  getSsoEnrollmentStatus,
  getTotpEnrollmentStatus,
  listIdpFederationProviders,
  listHrisBidirectionalSyncRuns,
  listHrisLifecycleSyncRuns,
  listSamlAutomatedRotationRuns,
  listSamlCertificateRotationRuns,
  listBulkIdpProvisioningRuns,
  listHrisPasswordlessUiRuns,
  listMobilePasskeyReadinessRuns,
  listNativeMobilePasskeyClientRuns,
  listNativeMobileAppStoreDistributionRuns,
  listSamlPasswordlessEnrollmentRuns,
  listSamlFederationMetadataUploads,
  listScimGroups,
  listScimUsers,
  registerIdpFederationProvider,
  runHrisBidirectionalSync,
  approveHrisLifecycleSyncRun,
  approveSamlAutomatedRotationRun,
  approveSamlCertificateRotationRun,
  approveBulkIdpProvisioningRun,
  approveHrisPasswordlessUiRun,
  approveMobilePasskeyReadinessRun,
  approveNativeMobilePasskeyClientRun,
  approveNativeMobileAppStoreDistributionRun,
  approveSamlPasswordlessEnrollmentRun,
  startHrisLifecycleSyncFromBidirectionalRun,
  startSamlAutomatedRotationFromRotationRun,
  startBulkIdpProvisioningFromUiRun,
  startHrisPasswordlessUiFromEnrollmentRun,
  startMobilePasskeyReadinessFromUiRun,
  startNativeMobilePasskeyClientFromReadinessRun,
  startNativeMobileAppStoreDistributionFromPasskeyClientRun,
  enrollSamlPasswordlessFromAutomatedRotationRun,
  submitSamlCertificateRotation,
  provisionScimGroup,
  provisionScimUser,
  startSsoEnrollment,
  startTotpEnrollment,
  type EnterpriseIdentityStatus,
  type IdpFederationProvider,
  type IdpFederationProviderList,
  type IdpFederationProviderRegisterInput,
  type IdpFederationProviderType,
  type IdpFederationStatus,
  type HrisBidirectionalSyncRun,
  type HrisBidirectionalSyncRunInput,
  type HrisBidirectionalSyncRunKind,
  type HrisBidirectionalSyncRunList,
  type HrisBidirectionalSyncRunResult,
  type HrisBidirectionalSyncRunStatus,
  type HrisBidirectionalSyncStatus,
  type HrisBidirectionalSyncTriggerSource,
  type HrisLifecycleSyncGateStatus,
  type HrisLifecycleSyncRun,
  type HrisLifecycleSyncRunList,
  type HrisLifecycleSyncRunResult,
  type HrisLifecycleSyncRunStatus,
  type HrisLifecycleSyncSubmitInput,
  type SamlAutomatedRotationGateStatus,
  type SamlAutomatedRotationRun,
  type SamlAutomatedRotationRunList,
  type SamlAutomatedRotationRunResult,
  type SamlAutomatedRotationRunStatus,
  type SamlAutomatedRotationSubmitInput,
  type BulkIdpProvisioningGateStatus,
  type BulkIdpProvisioningRun,
  type BulkIdpProvisioningRunList,
  type BulkIdpProvisioningRunResult,
  type BulkIdpProvisioningRunStatus,
  type BulkIdpProvisioningSubmitInput,
  type HrisPasswordlessUiGateStatus,
  type HrisPasswordlessUiRun,
  type HrisPasswordlessUiRunList,
  type HrisPasswordlessUiRunResult,
  type HrisPasswordlessUiRunStatus,
  type HrisPasswordlessUiSubmitInput,
  type MobilePasskeyReadinessGateStatus,
  type MobilePasskeyReadinessRun,
  type MobilePasskeyReadinessRunList,
  type MobilePasskeyReadinessRunResult,
  type MobilePasskeyReadinessRunStatus,
  type MobilePasskeyReadinessSubmitInput,
  type NativeMobilePasskeyClientGateStatus,
  type NativeMobilePasskeyClientRun,
  type NativeMobilePasskeyClientRunList,
  type NativeMobilePasskeyClientRunResult,
  type NativeMobilePasskeyClientRunStatus,
  type NativeMobilePasskeyClientSubmitInput,
  type NativeMobileAppStoreDistributionGateStatus,
  type NativeMobileAppStoreDistributionRun,
  type NativeMobileAppStoreDistributionRunList,
  type NativeMobileAppStoreDistributionRunResult,
  type NativeMobileAppStoreDistributionRunStatus,
  type NativeMobileAppStoreDistributionSubmitInput,
  type SamlPasswordlessEnrollmentGateStatus,
  type SamlPasswordlessEnrollmentRun,
  type SamlPasswordlessEnrollmentRunList,
  type SamlPasswordlessEnrollmentRunResult,
  type SamlPasswordlessEnrollmentRunStatus,
  type SamlPasswordlessEnrollmentSubmitInput,
  type SamlCertificateRotationGateStatus,
  type SamlCertificateRotationInput,
  type SamlCertificateRotationRun,
  type SamlCertificateRotationRunList,
  type SamlCertificateRotationRunResult,
  type SamlCertificateRotationStatus,
  uploadSamlFederationMetadata,
  type SamlFederationMetadataStatus,
  type SamlFederationMetadataUpload,
  type SamlFederationMetadataUploadInput,
  type SamlFederationMetadataUploadList,
  type SamlFederationMetadataUploadResult,
  type SamlMetadataValidationStatus,
  type ScimGroupList,
  type ScimGroupProvisionInput,
  type ScimGroupResource,
  type ScimMeta,
  type ScimProvisioningStatus,
  type ScimUserList,
  type ScimUserProvisionInput,
  type ScimUserResource,
  type SsoEnrollmentComplete,
  type SsoEnrollmentCompleteInput,
  type SsoEnrollmentStart,
  type SsoEnrollmentStatus,
  type TotpEnrollmentStart,
  type TotpEnrollmentStatus,
} from './enterprise';

export {
  getBillingInvoiceCollectionStatus,
  getBillingInvoicingStatus,
  getBillingStatus,
  getBillingUsageSummary,
  getStripeInvoicePdfStatus,
  getStripeLiveTaxApiStatus,
  getStripeChargeRetryStatus,
  getStripeLiveChargeRetryExecutionStatus,
  getStripeTaxCalculationStatus,
  invokeStripeLiveTaxApiFromTaxCalculationRun,
  listBillingInvoiceCollectionRuns,
  listBillingInvoicingRuns,
  listStripeInvoicePdfRuns,
  listStripeLiveTaxApiRuns,
  listStripeChargeRetryRuns,
  listStripeLiveChargeRetryExecutionRuns,
  listStripeTaxCalculationRuns,
  recordBillingUsageEvent,
  runBillingInvoiceCollection,
  runBillingInvoicingCycle,
  approveStripeInvoicePdfRun,
  approveStripeLiveTaxApiRun,
  approveStripeChargeRetryRun,
  approveStripeLiveChargeRetryExecutionRun,
  approveStripeTaxCalculationRun,
  submitStripeInvoicePdfRun,
  submitStripeTaxCalculationRun,
  submitStripeChargeRetryFromLiveTaxApiRun,
  submitStripeLiveChargeRetryExecutionFromChargeRetryRun,
  setupOrganizationBilling,
  disconnectPilotBilling,
  subscribeOrganizationBilling,
  type BillingInvoiceCollectionRun,
  type BillingInvoiceCollectionRunInput,
  type BillingInvoiceCollectionRunKind,
  type BillingInvoiceCollectionRunResult,
  type BillingInvoiceCollectionStatus,
  type StripeInvoicePdfGateStatus,
  type StripeInvoicePdfInput,
  type StripeInvoicePdfRun,
  type StripeInvoicePdfRunList,
  type StripeInvoicePdfRunResult,
  type StripeInvoicePdfRunStatus,
  type StripeLiveTaxApiGateStatus,
  type StripeLiveTaxApiInvokeInput,
  type StripeLiveTaxApiRun,
  type StripeLiveTaxApiRunList,
  type StripeLiveTaxApiRunResult,
  type StripeLiveTaxApiRunStatus,
  type StripeChargeRetryGateStatus,
  type StripeChargeRetryRun,
  type StripeChargeRetryRunList,
  type StripeChargeRetryRunResult,
  type StripeChargeRetryRunStatus,
  type StripeChargeRetrySubmitInput,
  type StripeLiveChargeRetryExecutionGateStatus,
  type StripeLiveChargeRetryExecutionRun,
  type StripeLiveChargeRetryExecutionRunList,
  type StripeLiveChargeRetryExecutionRunResult,
  type StripeLiveChargeRetryExecutionRunStatus,
  type StripeLiveChargeRetryExecutionSubmitInput,
  type StripeTaxCalculationGateStatus,
  type StripeTaxCalculationInput,
  type StripeTaxCalculationRun,
  type StripeTaxCalculationRunList,
  type StripeTaxCalculationRunResult,
  type StripeTaxCalculationRunStatus,
  type BillingInvoicingRun,
  type BillingInvoicingRunInput,
  type BillingInvoicingRunKind,
  type BillingInvoicingRunResult,
  type BillingInvoicingStatus,
  type BillingSetupResponse,
  type BillingStatus,
  type BillingSubscribeInput,
  type BillingSubscribeResponse,
  type BillingUsageMetricTotal,
  type BillingUsageRecordInput,
  type BillingUsageRecordResponse,
  type BillingUsageSummary,
  type OrganizationBillingSummary,
  type SubscriptionStatus,
} from './billing';

export {
  approveOAuthDeveloperApp,
  approveOAuthMarketplacePublishingRun,
  approvePublicOAuthMarketplaceListingRun,
  createOAuthDeveloperApp,
  createOrganizationApiKey,
  getApiKeyRateLimitStatus,
  getDeveloperPortal,
  getOAuthMarketplacePublishingStatus,
  getPublicOAuthMarketplaceListingStatus,
  getOrgAdminStatus,
  getOrganizationAdminSummary,
  getOrganizationApiKey,
  listOAuthDeveloperApps,
  listOAuthMarketplacePublishingRuns,
  listPublicOAuthMarketplaceListingRuns,
  listOrganizationApiKeys,
  revokeOrganizationApiKey,
  rotateOrganizationApiKey,
  startOAuthMarketplacePublishingFromApp,
  startPublicOAuthMarketplaceListingFromPublishingRun,
  type ApiKey,
  type ApiKeyCreateInput,
  type ApiKeyCreateResponse,
  type ApiKeyRateLimitStatus,
  type ApiKeyRotateResponse,
  type ApiKeyScope,
  type DeveloperPortal,
  type OAuthDeveloperApp,
  type OAuthDeveloperAppCreateInput,
  type OAuthDeveloperAppStatus,
  type OAuthMarketplacePublishingGateStatus,
  type OAuthMarketplacePublishingRun,
  type OAuthMarketplacePublishingRunList,
  type OAuthMarketplacePublishingRunResult,
  type OAuthMarketplacePublishingRunStatus,
  type OAuthMarketplacePublishingSubmitInput,
  type PublicOAuthMarketplaceListingGateStatus,
  type PublicOAuthMarketplaceListingRun,
  type PublicOAuthMarketplaceListingRunList,
  type PublicOAuthMarketplaceListingRunResult,
  type PublicOAuthMarketplaceListingRunStatus,
  type PublicOAuthMarketplaceListingSubmitInput,
  type OrgAdminStatus,
  type OrganizationAdminSummary,
} from './orgAdmin';

export {
  getCaseMessageThread,
  getMessagingCenterStatus,
  postCaseMessageThreadReply,
  type CaseMessageThread,
  type MessagingCenterStatus,
  type SendMessageInput,
  type ThreadMessage,
  type MessageSenderRole,
} from './messaging';

export {
  createConsentRecord,
  createRetentionPolicy,
  approveAutonomousBureauFilingRun,
  approveFullyAutonomousBureauApiFilingRun,
  approveUnsupervisedAutonomousFilingLoopRun,
  approveBureauLiveApiRun,
  approveBureauRefilingRun,
  approveBureauUnsupervisedRefilingRun,
  approveDisputeBureauSubmissionRun,
  approveDisputeFilingPrepRun,
  executeFullyAutonomousBureauApiFilingFromFilingRun,
  startUnsupervisedAutonomousFilingLoopFromApiFilingRun,
  fileAutonomousBureauFilingFromLiveApiRun,
  getAutonomousBureauFilingStatus,
  getFullyAutonomousBureauApiFilingStatus,
  getUnsupervisedAutonomousFilingLoopStatus,
  getBureauLiveApiStatus,
  getBureauRefilingStatus,
  getBureauUnsupervisedRefilingStatus,
  getComplianceCenterStatus,
  getConsentRecord,
  getDisputeBureauSubmissionStatus,
  getDisputeFilingPrepStatus,
  getRetentionEnforcementStatus,
  getRetentionPolicy,
  invokeBureauLiveApiFromSubmissionRun,
  listAutonomousBureauFilingRuns,
  listFullyAutonomousBureauApiFilingRuns,
  listUnsupervisedAutonomousFilingLoopRuns,
  listBureauLiveApiRuns,
  listBureauRefilingRuns,
  listBureauUnsupervisedRefilingRuns,
  listConsentRecords,
  listDisputeBureauSubmissionRuns,
  listDisputeFilingPrepRuns,
  listRetentionEnforcementRuns,
  listRetentionPolicies,
  refileBureauFromAutonomousFilingRun,
  startBureauUnsupervisedRefilingFromRefilingRun,
  runRetentionEnforcement,
  submitDisputeBureauSubmission,
  submitDisputeFilingPrep,
  updateRetentionPolicy,
  uploadSignedConsentRecord,
  getClientConsentGaps,
  getConsentTemplatePreviewUrl,
  listConsentDocumentTemplates,
  updateConsentDocumentTemplate,
  withdrawConsentRecord,
  type AutonomousBureauFilingRun,
  type AutonomousBureauFilingRunResult,
  type AutonomousBureauFilingRunStatus,
  type AutonomousBureauFilingStatus,
  type AutonomousBureauFilingSubmitRequest,
  type FullyAutonomousBureauApiFilingRun,
  type FullyAutonomousBureauApiFilingRunResult,
  type FullyAutonomousBureauApiFilingRunStatus,
  type FullyAutonomousBureauApiFilingStatus,
  type FullyAutonomousBureauApiFilingSubmitRequest,
  type UnsupervisedAutonomousFilingLoopRun,
  type UnsupervisedAutonomousFilingLoopRunResult,
  type UnsupervisedAutonomousFilingLoopRunStatus,
  type UnsupervisedAutonomousFilingLoopStatus,
  type UnsupervisedAutonomousFilingLoopSubmitRequest,
  type BureauLiveApiInvokeRequest,
  type BureauLiveApiRun,
  type BureauLiveApiRunResult,
  type BureauLiveApiRunStatus,
  type BureauLiveApiStatus,
  type BureauRefilingRun,
  type BureauRefilingRunResult,
  type BureauRefilingRunStatus,
  type BureauRefilingStatus,
  type BureauRefilingSubmitRequest,
  type BureauUnsupervisedRefilingRun,
  type BureauUnsupervisedRefilingRunResult,
  type BureauUnsupervisedRefilingRunStatus,
  type BureauUnsupervisedRefilingStatus,
  type BureauUnsupervisedRefilingSubmitRequest,
  type ListBureauUnsupervisedRefilingRunsParams,
  type ClientConsentGaps,
  type ConsentDocumentTemplate,
  type ConsentDocumentTemplateKey,
  type UpdateConsentDocumentTemplateInput,
  type ComplianceCenterStatus,
  type ConsentRecord,
  type ConsentSignatureMethod,
  type ConsentStatus,
  type ConsentType,
  type CreateConsentRecordInput,
  type CreateRetentionPolicyInput,
  type DisputeBureauSubmissionRequest,
  type DisputeBureauSubmissionRun,
  type DisputeBureauSubmissionRunResult,
  type DisputeBureauSubmissionRunStatus,
  type DisputeBureauSubmissionStatus,
  type DisputeFilingPrepRequest,
  type DisputeFilingPrepRun,
  type DisputeFilingPrepRunResult,
  type DisputeFilingPrepRunStatus,
  type DisputeFilingPrepStatus,
  type EnforcementRunStatus,
  type EnforcementTriggerSource,
  type ListAutonomousBureauFilingRunsParams,
  type ListFullyAutonomousBureauApiFilingRunsParams,
  type ListUnsupervisedAutonomousFilingLoopRunsParams,
  type ListBureauRefilingRunsParams,
  type ListBureauLiveApiRunsParams,
  type ListConsentRecordsParams,
  type ListDisputeBureauSubmissionRunsParams,
  type ListDisputeFilingPrepRunsParams,
  type ListRetentionEnforcementRunsParams,
  type ListRetentionPoliciesParams,
  type RetentionEnforcementRun,
  type RetentionEnforcementRunResult,
  type RetentionEnforcementStatus,
  type RetentionPolicy,
  type RetentionScope,
  type UpdateRetentionPolicyInput,
  type UploadSignedConsentInput,
} from './compliance';

export {
  createAccount,
  createAccountDisputeDraftReviewTask,
  createAccountDisputeDraftLlmAugment,
  createAccountDisputeLetterDraft,
  createAccountDisputeLetterReviewTask,
  approveAccountDisputeLetter,
  sendAccountDisputeLetter,
  voidAccountDisputeLetter,
  deleteAccount,
  getAccount,
  getAccountDisputeDraft,
  getAccountIntelligenceSummary,
  generateAccountLlmRecommendation,
  listAccountDisputeDraftLlmAugments,
  listAccountDisputeLetters,
  getAccountDisputeLetter,
  downloadAccountDisputeLetterExport,
  markAccountAwaitingDisputeResponse,
  markAccountDisputeResponseReceived,
  escalateAccountOverdueInvestigation,
  listAccounts,
  listCaseAccounts,
  listClientAccounts,
  updateAccount,
  type Account,
  type AccountDisputeDraft,
  type DisputeReasonSuggestion,
  type DisputeRecipientType,
  type DisputeResponseOutcome,
  type MissingEvidenceItem,
  type AccountIntelligenceSummary,
  type AccountLlmRecommendation,
  type CrossBureauIntelligenceSummary,
  type CreateAccountInput,
  type DisputeLetter,
  type DisputeLetterExportFormat,
  type DisputeLetterStatus,
  type LlmDisputeDraftAugment,
  type LlmDisputeDraftAugmentInput,
  type LlmDisputeDraftAugmentStatusValue,
  type ListAccountsParams,
  type NextActionItem,
  type UpdateAccountInput,
} from './accounts';

export {
  compareDocumentParsedCreditReport,
  confirmDocumentResolution,
  createDocumentParsedCreditReportReviewTask,
  importParsedCreditReportAccounts,
  deleteDocument,
  enqueueBatchDocumentSummaryRun,
  extractDocumentMetadata,
  generateDocumentLlmSummary,
  getBatchLlmSummaryStatus,
  getDocument,
  getDocumentDuplicateGroup,
  getDocumentDownloadUrl,
  getDocumentMetadata,
  getDocumentOcr,
  getDocumentParsedCreditReportAccountCandidates,
  getDocumentParsedCreditReport,
  getDocumentMetro2Findings,
  getDocumentFcraFindings,
  getDocumentResolutions,
  listBatchDocumentSummaryRuns,
  listDocumentVersions,
  listDocuments,
  rejectDocumentResolution,
  resolveDocumentEntities,
  retryDocumentOcr,
  updateDocument,
  uploadDocument,
  uploadDocumentVersion,
  type BatchDocumentSummaryEnqueueResponse,
  type BatchDocumentSummaryRun,
  type BatchLlmSummaryStatus,
  type Document,
  type DocumentDuplicateGroup,
  type DocumentEntityResolution,
  type DocumentLlmSummary,
  type DocumentMetadata,
  type DocumentOcrResult,
  type DocumentParsedCreditReportAccountCandidates,
  type DocumentParsedCreditReport,
  type DocumentParsedCreditReportComparison,
  type DocumentMetro2Findings,
  type DocumentFcraFindings,
  type ImportParsedReportAccountsRequest,
  type ImportParsedReportAccountsResponse,
  type ImportedParsedReportAccountItem,
  type DocumentResolutions,
  type DocumentVersion,
  type ListDocumentsParams,
  type Metro2Finding,
  type Metro2FindingSummary,
  type FcraFinding,
  type FcraFindingSummary,
  type TradelineChronologyEvent,
  type TradelineChronologyEventType,
  type TradelineChronologyItem,
  type TradelineChronologySnapshot,
  type TradelineChronologySummary,
  type ComplianceEvidenceSummary,
  type ComplianceEvidenceReportLink,
  type ComplianceEvidenceExhibitLink,
  type ComplianceEvidenceLinkItem,
  type LitigationStrengthSummary,
  type LitigationStrengthIssue,
  type DisputeStrategySummary,
  type DisputeStrategyStageKind,
  type DisputeStrategyStage,
  type AccountDisputeStrategy,
  type ParsedReportAccountChange,
  type ParsedReportAccountCandidate,
  type ParsedReportComparisonSummary,
  type ParsedReportFieldDiff,
  type UpdateDocumentInput,
  type UploadDocumentInput,
} from './documents';

export {
  completeTask,
  createTask,
  deleteTask,
  getTask,
  listTasks,
  reopenTask,
  updateTask,
  type CreateTaskInput,
  type ListTasksParams,
  type Task,
  type UpdateTaskInput,
} from './tasks';

export {
  getTimelineEvent,
  listTimelineEvents,
  type ListTimelineParams,
  type TimelineEvent,
} from './timeline';

export {
  createNotification,
  getNotificationEmailDeliveryStatus,
  getNotificationSmsDeliveryStatus,
  getSmsMarketingCampaignStatus,
  getSmsDeliverabilityDashboardStatus,
  getSmsDeliverabilitySummary,
  getUnreadNotificationCount,
  listNotificationEmailDeliveries,
  listNotificationSmsDeliveries,
  listSmsMarketingCampaignRuns,
  listNotifications,
  markAllNotificationsRead,
  markNotificationRead,
  sendNotificationEmail,
  sendNotificationSms,
  runSmsMarketingCampaign,
  type CreateNotificationInput,
  type EmailDeliveryAttempt,
  type EmailDeliveryLog,
  type EmailDeliveryStatus,
  type ListNotificationsParams,
  type Notification,
  type NotificationCategory,
  type SendNotificationEmailInput,
  type SendNotificationSmsInput,
  type SmsDeliveryAttempt,
  type SmsDeliveryLog,
  type SmsDeliveryStatus,
  type SmsDeliverabilityCampaignOutcome,
  type SmsDeliverabilityDashboardStatus,
  type SmsDeliverabilityMetrics,
  type SmsMarketingCampaignRun,
  type SmsMarketingCampaignRunInput,
  type SmsMarketingCampaignRunResult,
  type SmsMarketingCampaignRunStatus,
  type SmsMarketingCampaignStatus,
  type SmsMarketingTriggerSource,
  type UnreadCountResponse,
} from './notifications';

export {
  downloadPortalConsentPreview,
  getPortalCase,
  getPortalConsentPreviewUrl,
  getPortalMe,
  getPortalPushStatus,
  listPortalCaseDocuments,
  listPortalCaseConsents,
  listPortalCaseMessages,
  listPortalCases,
  portalLogin,
  portalRefresh,
  provisionClientPortalUser,
  sendPortalCaseMessage,
  signPortalCaseConsent,
  subscribePortalPush,
  unsubscribePortalPush,
  uploadPortalCaseDocument,
  getClientPortalUser,
  updateClientPortalUser,
  revokeClientPortalUser,
  type ClientPortalUser,
  type PortalCaseConsentsResponse,
  type PortalCaseDetail,
  type PortalCaseDocumentsResponse,
  type PortalCaseMessageThread,
  type PortalConsentRequirement,
  type SignPortalConsentInput,
  type PortalCaseProgressResponse,
  type PortalCaseStage,
  type PortalCaseStatus,
  type PortalCaseSummary,
  type PortalDocument,
  type PortalLoginInput,
  type PortalMeResponse,
  type PortalPushStatus,
  type PortalPushSubscribeInput,
  type PortalPushSubscription,
  type PortalThreadMessage,
  type PortalTokenResponse,
  type ProvisionPortalUserInput,
  type SendPortalMessageInput,
  type UpdatePortalUserInput,
  type UploadPortalCaseDocumentInput,
} from './portal';

export {
  completeClientEnrollment,
  getClientEnrollmentCheckoutSession,
  getClientEnrollmentStatus,
  registerClientEnrollment,
  startClientEnrollmentCheckout,
  type ClientEnrollmentCheckoutResult,
  type ClientEnrollmentCompleteResult,
  type ClientEnrollmentIntakeInput,
  type ClientEnrollmentSession,
  type ClientEnrollmentStatus,
} from './enrollment';

export interface HealthResponse {
  status: string;
  version: string;
  environment: string;
}

export interface VersionResponse {
  version: string;
  name: string;
}

export async function getHealth(): Promise<HealthResponse> {
  return request<HealthResponse>(apiPath('/health'), { auth: false });
}

export async function getVersion(): Promise<VersionResponse> {
  return request<VersionResponse>(apiPath('/version'), { auth: false });
}
