import { apiPath, request } from './http';

export {
  ApiClientError,
  ApiNotImplementedError,
  apiPath,
  configureApiClient,
  getAccessToken,
  getApiBaseUrl,
  notImplemented,
  request,
  setAccessToken,
  uploadRequest,
  type ApiClientConfig,
  type RequestOptions,
} from './http';

export {
  getCurrentUser,
  login,
  refreshToken,
  type LoginRequest,
  type RefreshTokenRequest,
  type TokenResponse,
  type User,
} from './auth';

export {
  getDashboard,
  type DashboardAccounts,
  type DashboardAlertItem,
  type DashboardAlerts,
  type DashboardAlertSeverity,
  type DashboardAlertType,
  type DashboardCases,
  type DashboardDocuments,
  type DashboardOperations,
  type DashboardOverview,
  type DashboardPerformance,
  type DashboardProcessing,
  type DashboardResponse,
  type DashboardTasks,
  type DashboardTimelineItem,
} from './dashboard';

export {
  getBureauPerformanceReporting,
  getEnterpriseReportingStatus,
  getMaterializedReportingStatus,
  getOperationsReporting,
  getPredictiveAnalyticsStatus,
  getPredictiveOutcomesReporting,
  getRevenueAnalyticsReporting,
  getTeamProductivityReporting,
  listMaterializedReportingRefreshRuns,
  refreshMaterializedReportingViews,
  refreshPredictiveOutcomesReporting,
  type BureauPerformanceItem,
  type BureauPerformanceReporting,
  type BureauPerformanceReportingResponse,
  type ClientReportingMetrics,
  type EnterpriseReportingStatus,
  type MaterializedReportingStatus,
  type NotificationReportingMetrics,
  type OperationsReporting,
  type OperationsReportingResponse,
  type PredictiveAnalyticsStatus,
  type PredictiveOutcomeRefreshResult,
  type PredictiveOutcomeRefreshRun,
  type PredictiveOutcomes,
  type PredictiveOutcomesReportingResponse,
  type ReportingMvRefreshResult,
  type ReportingMvRefreshRun,
  type RevenueAnalytics,
  type RevenueAnalyticsReportingResponse,
  type TeamMemberProductivity,
  type TeamProductivityReporting,
  type TeamProductivityReportingResponse,
} from './reporting';

export {
  createCase,
  deleteCase,
  generateCaseLlmSummary,
  getCase,
  listCases,
  updateCase,
  type Case,
  type CaseLlmSummary,
  type CreateCaseInput,
  type ListCasesParams,
  type UpdateCaseInput,
} from './cases';

export {
  createClient,
  createClientContact,
  deleteClient,
  deleteClientContact,
  getClient,
  getClientContact,
  listClientContacts,
  listClients,
  updateClient,
  updateClientContact,
  type Client,
  type ClientContact,
  type ClientStatus,
  type ContactRelationship,
  type CreateClientContactInput,
  type CreateClientInput,
  type ListClientContactsParams,
  type ListClientsParams,
  type UpdateClientContactInput,
  type UpdateClientInput,
} from './clients';

export {
  approveAgentExecutionStep,
  approveAgentArbitraryExecutionRun,
  approveAgentSupervisedLoopRun,
  approveAgentUnsupervisedLoopRun,
  approveAgentToolInvocationRequest,
  getAgentArbitraryExecutionStatus,
  getAgentExecutionStatus,
  getAgentExternalToolCallingStatus,
  getAgentObservabilityStatus,
  getAgentSupervisedLoopStatus,
  getAgentUnsupervisedLoopStatus,
  getLlmDisputeDraftAugmentStatus,
  getLlmStatus,
  listAgentArbitraryExecutionRuns,
  listAgentExecutionSteps,
  listAgentObservabilityRuns,
  listAgentSupervisedLoopRuns,
  listAgentUnsupervisedLoopRuns,
  listAgentToolInvocationRequests,
  runAgentObservabilityScaffold,
  startAgentArbitraryExecutionFromUnsupervisedRun,
  startAgentSupervisedLoopFromToolRequest,
  startAgentUnsupervisedLoopFromSupervisedRun,
  submitAgentExecutionStep,
  submitAgentToolInvocationRequest,
  type AgentArbitraryExecutionGateStatus,
  type AgentArbitraryExecutionRun,
  type AgentArbitraryExecutionRunResult,
  type AgentArbitraryExecutionStatus,
  type AgentArbitraryExecutionSubmitInput,
  type AgentExecutionStatus,
  type AgentExecutionStep,
  type AgentExecutionStepResult,
  type AgentExecutionStepStatus,
  type AgentExecutionStepSubmitInput,
  type AgentExternalToolCallingStatus,
  type AgentExternalToolKind,
  type AgentObservabilityKind,
  type AgentObservabilityRun,
  type AgentObservabilityRunInput,
  type AgentObservabilityRunResult,
  type AgentObservabilityRunStatus,
  type AgentObservabilityStatus,
  type AgentObservabilityTriggerSource,
  type AgentSupervisedLoopGateStatus,
  type AgentSupervisedLoopRun,
  type AgentSupervisedLoopRunResult,
  type AgentSupervisedLoopStatus,
  type AgentSupervisedLoopSubmitInput,
  type AgentUnsupervisedLoopGateStatus,
  type AgentUnsupervisedLoopRun,
  type AgentUnsupervisedLoopRunResult,
  type AgentUnsupervisedLoopStatus,
  type AgentUnsupervisedLoopSubmitInput,
  type AgentToolInvocationRequest,
  type AgentToolInvocationRequestResult,
  type AgentToolInvocationStatus,
  type AgentToolInvocationSubmitInput,
  type LlmGateStatus,
  type LlmDisputeDraftAugmentStatus,
} from './llm';

export {
  completeSsoEnrollment,
  confirmTotpEnrollment,
  disableTotpEnrollment,
  getEnterpriseIdentityStatus,
  getHrisBidirectionalSyncStatus,
  getHrisLifecycleSyncStatus,
  getIdpFederationStatus,
  getSamlAutomatedRotationStatus,
  getSamlCertificateRotationStatus,
  getSamlPasswordlessEnrollmentStatus,
  getSamlFederationMetadataStatus,
  getScimProvisioningStatus,
  getSsoEnrollmentStatus,
  getTotpEnrollmentStatus,
  listIdpFederationProviders,
  listHrisBidirectionalSyncRuns,
  listHrisLifecycleSyncRuns,
  listSamlAutomatedRotationRuns,
  listSamlCertificateRotationRuns,
  listSamlPasswordlessEnrollmentRuns,
  listSamlFederationMetadataUploads,
  listScimGroups,
  listScimUsers,
  registerIdpFederationProvider,
  runHrisBidirectionalSync,
  approveHrisLifecycleSyncRun,
  approveSamlAutomatedRotationRun,
  approveSamlCertificateRotationRun,
  approveSamlPasswordlessEnrollmentRun,
  startHrisLifecycleSyncFromBidirectionalRun,
  startSamlAutomatedRotationFromRotationRun,
  enrollSamlPasswordlessFromAutomatedRotationRun,
  submitSamlCertificateRotation,
  provisionScimGroup,
  provisionScimUser,
  startSsoEnrollment,
  startTotpEnrollment,
  type EnterpriseIdentityStatus,
  type IdpFederationProvider,
  type IdpFederationProviderList,
  type IdpFederationProviderRegisterInput,
  type IdpFederationProviderType,
  type IdpFederationStatus,
  type HrisBidirectionalSyncRun,
  type HrisBidirectionalSyncRunInput,
  type HrisBidirectionalSyncRunKind,
  type HrisBidirectionalSyncRunList,
  type HrisBidirectionalSyncRunResult,
  type HrisBidirectionalSyncRunStatus,
  type HrisBidirectionalSyncStatus,
  type HrisBidirectionalSyncTriggerSource,
  type HrisLifecycleSyncGateStatus,
  type HrisLifecycleSyncRun,
  type HrisLifecycleSyncRunList,
  type HrisLifecycleSyncRunResult,
  type HrisLifecycleSyncRunStatus,
  type HrisLifecycleSyncSubmitInput,
  type SamlAutomatedRotationGateStatus,
  type SamlAutomatedRotationRun,
  type SamlAutomatedRotationRunList,
  type SamlAutomatedRotationRunResult,
  type SamlAutomatedRotationRunStatus,
  type SamlAutomatedRotationSubmitInput,
  type SamlPasswordlessEnrollmentGateStatus,
  type SamlPasswordlessEnrollmentRun,
  type SamlPasswordlessEnrollmentRunList,
  type SamlPasswordlessEnrollmentRunResult,
  type SamlPasswordlessEnrollmentRunStatus,
  type SamlPasswordlessEnrollmentSubmitInput,
  type SamlCertificateRotationGateStatus,
  type SamlCertificateRotationInput,
  type SamlCertificateRotationRun,
  type SamlCertificateRotationRunList,
  type SamlCertificateRotationRunResult,
  type SamlCertificateRotationStatus,
  uploadSamlFederationMetadata,
  type SamlFederationMetadataStatus,
  type SamlFederationMetadataUpload,
  type SamlFederationMetadataUploadInput,
  type SamlFederationMetadataUploadList,
  type SamlFederationMetadataUploadResult,
  type SamlMetadataValidationStatus,
  type ScimGroupList,
  type ScimGroupProvisionInput,
  type ScimGroupResource,
  type ScimMeta,
  type ScimProvisioningStatus,
  type ScimUserList,
  type ScimUserProvisionInput,
  type ScimUserResource,
  type SsoEnrollmentComplete,
  type SsoEnrollmentCompleteInput,
  type SsoEnrollmentStart,
  type SsoEnrollmentStatus,
  type TotpEnrollmentStart,
  type TotpEnrollmentStatus,
} from './enterprise';

export {
  getBillingInvoiceCollectionStatus,
  getBillingInvoicingStatus,
  getBillingStatus,
  getBillingUsageSummary,
  getStripeInvoicePdfStatus,
  getStripeLiveTaxApiStatus,
  getStripeChargeRetryStatus,
  getStripeTaxCalculationStatus,
  invokeStripeLiveTaxApiFromTaxCalculationRun,
  listBillingInvoiceCollectionRuns,
  listBillingInvoicingRuns,
  listStripeInvoicePdfRuns,
  listStripeLiveTaxApiRuns,
  listStripeChargeRetryRuns,
  listStripeTaxCalculationRuns,
  recordBillingUsageEvent,
  runBillingInvoiceCollection,
  runBillingInvoicingCycle,
  approveStripeInvoicePdfRun,
  approveStripeLiveTaxApiRun,
  approveStripeChargeRetryRun,
  approveStripeTaxCalculationRun,
  submitStripeInvoicePdfRun,
  submitStripeTaxCalculationRun,
  submitStripeChargeRetryFromLiveTaxApiRun,
  setupOrganizationBilling,
  subscribeOrganizationBilling,
  type BillingInvoiceCollectionRun,
  type BillingInvoiceCollectionRunInput,
  type BillingInvoiceCollectionRunKind,
  type BillingInvoiceCollectionRunResult,
  type BillingInvoiceCollectionStatus,
  type StripeInvoicePdfGateStatus,
  type StripeInvoicePdfInput,
  type StripeInvoicePdfRun,
  type StripeInvoicePdfRunList,
  type StripeInvoicePdfRunResult,
  type StripeInvoicePdfRunStatus,
  type StripeLiveTaxApiGateStatus,
  type StripeLiveTaxApiInvokeInput,
  type StripeLiveTaxApiRun,
  type StripeLiveTaxApiRunList,
  type StripeLiveTaxApiRunResult,
  type StripeLiveTaxApiRunStatus,
  type StripeChargeRetryGateStatus,
  type StripeChargeRetryRun,
  type StripeChargeRetryRunList,
  type StripeChargeRetryRunResult,
  type StripeChargeRetryRunStatus,
  type StripeChargeRetrySubmitInput,
  type StripeTaxCalculationGateStatus,
  type StripeTaxCalculationInput,
  type StripeTaxCalculationRun,
  type StripeTaxCalculationRunList,
  type StripeTaxCalculationRunResult,
  type StripeTaxCalculationRunStatus,
  type BillingInvoicingRun,
  type BillingInvoicingRunInput,
  type BillingInvoicingRunKind,
  type BillingInvoicingRunResult,
  type BillingInvoicingStatus,
  type BillingSetupResponse,
  type BillingStatus,
  type BillingSubscribeInput,
  type BillingSubscribeResponse,
  type BillingUsageMetricTotal,
  type BillingUsageRecordInput,
  type BillingUsageRecordResponse,
  type BillingUsageSummary,
  type OrganizationBillingSummary,
  type SubscriptionStatus,
} from './billing';

export {
  createOrganizationApiKey,
  getApiKeyRateLimitStatus,
  getDeveloperPortal,
  getOrgAdminStatus,
  getOrganizationAdminSummary,
  getOrganizationApiKey,
  listOrganizationApiKeys,
  revokeOrganizationApiKey,
  rotateOrganizationApiKey,
  type ApiKey,
  type ApiKeyCreateInput,
  type ApiKeyCreateResponse,
  type ApiKeyRateLimitStatus,
  type ApiKeyRotateResponse,
  type ApiKeyScope,
  type DeveloperPortal,
  type OrgAdminStatus,
  type OrganizationAdminSummary,
} from './orgAdmin';

export {
  getCaseMessageThread,
  getMessagingCenterStatus,
  postCaseMessageThreadReply,
  type CaseMessageThread,
  type MessagingCenterStatus,
  type SendMessageInput,
  type ThreadMessage,
  type MessageSenderRole,
} from './messaging';

export {
  createConsentRecord,
  createRetentionPolicy,
  approveAutonomousBureauFilingRun,
  approveBureauLiveApiRun,
  approveBureauRefilingRun,
  approveBureauUnsupervisedRefilingRun,
  approveDisputeBureauSubmissionRun,
  approveDisputeFilingPrepRun,
  fileAutonomousBureauFilingFromLiveApiRun,
  getAutonomousBureauFilingStatus,
  getBureauLiveApiStatus,
  getBureauRefilingStatus,
  getBureauUnsupervisedRefilingStatus,
  getComplianceCenterStatus,
  getConsentRecord,
  getDisputeBureauSubmissionStatus,
  getDisputeFilingPrepStatus,
  getRetentionEnforcementStatus,
  getRetentionPolicy,
  invokeBureauLiveApiFromSubmissionRun,
  listAutonomousBureauFilingRuns,
  listBureauLiveApiRuns,
  listBureauRefilingRuns,
  listBureauUnsupervisedRefilingRuns,
  listConsentRecords,
  listDisputeBureauSubmissionRuns,
  listDisputeFilingPrepRuns,
  listRetentionEnforcementRuns,
  listRetentionPolicies,
  refileBureauFromAutonomousFilingRun,
  startBureauUnsupervisedRefilingFromRefilingRun,
  runRetentionEnforcement,
  submitDisputeBureauSubmission,
  submitDisputeFilingPrep,
  updateRetentionPolicy,
  withdrawConsentRecord,
  type AutonomousBureauFilingRun,
  type AutonomousBureauFilingRunResult,
  type AutonomousBureauFilingRunStatus,
  type AutonomousBureauFilingStatus,
  type AutonomousBureauFilingSubmitRequest,
  type BureauLiveApiInvokeRequest,
  type BureauLiveApiRun,
  type BureauLiveApiRunResult,
  type BureauLiveApiRunStatus,
  type BureauLiveApiStatus,
  type BureauRefilingRun,
  type BureauRefilingRunResult,
  type BureauRefilingRunStatus,
  type BureauRefilingStatus,
  type BureauRefilingSubmitRequest,
  type BureauUnsupervisedRefilingRun,
  type BureauUnsupervisedRefilingRunResult,
  type BureauUnsupervisedRefilingRunStatus,
  type BureauUnsupervisedRefilingStatus,
  type BureauUnsupervisedRefilingSubmitRequest,
  type ListBureauUnsupervisedRefilingRunsParams,
  type ComplianceCenterStatus,
  type ConsentRecord,
  type ConsentStatus,
  type ConsentType,
  type CreateConsentRecordInput,
  type CreateRetentionPolicyInput,
  type DisputeBureauSubmissionRequest,
  type DisputeBureauSubmissionRun,
  type DisputeBureauSubmissionRunResult,
  type DisputeBureauSubmissionRunStatus,
  type DisputeBureauSubmissionStatus,
  type DisputeFilingPrepRequest,
  type DisputeFilingPrepRun,
  type DisputeFilingPrepRunResult,
  type DisputeFilingPrepRunStatus,
  type DisputeFilingPrepStatus,
  type EnforcementRunStatus,
  type EnforcementTriggerSource,
  type ListAutonomousBureauFilingRunsParams,
  type ListBureauRefilingRunsParams,
  type ListBureauLiveApiRunsParams,
  type ListConsentRecordsParams,
  type ListDisputeBureauSubmissionRunsParams,
  type ListDisputeFilingPrepRunsParams,
  type ListRetentionEnforcementRunsParams,
  type ListRetentionPoliciesParams,
  type RetentionEnforcementRun,
  type RetentionEnforcementRunResult,
  type RetentionEnforcementStatus,
  type RetentionPolicy,
  type RetentionScope,
  type UpdateRetentionPolicyInput,
} from './compliance';

export {
  createAccount,
  createAccountDisputeDraftReviewTask,
  createAccountDisputeDraftLlmAugment,
  createAccountDisputeLetterDraft,
  createAccountDisputeLetterReviewTask,
  approveAccountDisputeLetter,
  sendAccountDisputeLetter,
  voidAccountDisputeLetter,
  deleteAccount,
  getAccount,
  getAccountDisputeDraft,
  getAccountIntelligenceSummary,
  listAccountDisputeDraftLlmAugments,
  listAccountDisputeLetters,
  getAccountDisputeLetter,
  downloadAccountDisputeLetterExport,
  markAccountAwaitingDisputeResponse,
  markAccountDisputeResponseReceived,
  escalateAccountOverdueInvestigation,
  listAccounts,
  listCaseAccounts,
  updateAccount,
  type Account,
  type AccountDisputeDraft,
  type DisputeReasonSuggestion,
  type DisputeRecipientType,
  type DisputeResponseOutcome,
  type MissingEvidenceItem,
  type AccountIntelligenceSummary,
  type CreateAccountInput,
  type DisputeLetter,
  type DisputeLetterExportFormat,
  type DisputeLetterStatus,
  type LlmDisputeDraftAugment,
  type LlmDisputeDraftAugmentInput,
  type LlmDisputeDraftAugmentStatusValue,
  type ListAccountsParams,
  type NextActionItem,
  type UpdateAccountInput,
} from './accounts';

export {
  compareDocumentParsedCreditReport,
  confirmDocumentResolution,
  createDocumentParsedCreditReportReviewTask,
  deleteDocument,
  enqueueBatchDocumentSummaryRun,
  extractDocumentMetadata,
  generateDocumentLlmSummary,
  getBatchLlmSummaryStatus,
  getDocument,
  getDocumentDuplicateGroup,
  getDocumentDownloadUrl,
  getDocumentMetadata,
  getDocumentOcr,
  getDocumentParsedCreditReportAccountCandidates,
  getDocumentParsedCreditReport,
  getDocumentResolutions,
  listBatchDocumentSummaryRuns,
  listDocumentVersions,
  listDocuments,
  rejectDocumentResolution,
  resolveDocumentEntities,
  retryDocumentOcr,
  updateDocument,
  uploadDocument,
  uploadDocumentVersion,
  type BatchDocumentSummaryEnqueueResponse,
  type BatchDocumentSummaryRun,
  type BatchLlmSummaryStatus,
  type Document,
  type DocumentDuplicateGroup,
  type DocumentEntityResolution,
  type DocumentLlmSummary,
  type DocumentMetadata,
  type DocumentOcrResult,
  type DocumentParsedCreditReportAccountCandidates,
  type DocumentParsedCreditReport,
  type DocumentParsedCreditReportComparison,
  type DocumentResolutions,
  type DocumentVersion,
  type ListDocumentsParams,
  type ParsedReportAccountChange,
  type ParsedReportAccountCandidate,
  type ParsedReportComparisonSummary,
  type UpdateDocumentInput,
  type UploadDocumentInput,
} from './documents';

export {
  completeTask,
  createTask,
  deleteTask,
  getTask,
  listTasks,
  reopenTask,
  updateTask,
  type CreateTaskInput,
  type ListTasksParams,
  type Task,
  type UpdateTaskInput,
} from './tasks';

export {
  getTimelineEvent,
  listTimelineEvents,
  type ListTimelineParams,
  type TimelineEvent,
} from './timeline';

export {
  createNotification,
  getNotificationEmailDeliveryStatus,
  getNotificationSmsDeliveryStatus,
  getSmsMarketingCampaignStatus,
  getSmsDeliverabilityDashboardStatus,
  getSmsDeliverabilitySummary,
  getUnreadNotificationCount,
  listNotificationEmailDeliveries,
  listNotificationSmsDeliveries,
  listSmsMarketingCampaignRuns,
  listNotifications,
  markAllNotificationsRead,
  markNotificationRead,
  sendNotificationEmail,
  sendNotificationSms,
  runSmsMarketingCampaign,
  type CreateNotificationInput,
  type EmailDeliveryAttempt,
  type EmailDeliveryLog,
  type EmailDeliveryStatus,
  type ListNotificationsParams,
  type Notification,
  type NotificationCategory,
  type SendNotificationEmailInput,
  type SendNotificationSmsInput,
  type SmsDeliveryAttempt,
  type SmsDeliveryLog,
  type SmsDeliveryStatus,
  type SmsDeliverabilityCampaignOutcome,
  type SmsDeliverabilityDashboardStatus,
  type SmsDeliverabilityMetrics,
  type SmsMarketingCampaignRun,
  type SmsMarketingCampaignRunInput,
  type SmsMarketingCampaignRunResult,
  type SmsMarketingCampaignRunStatus,
  type SmsMarketingCampaignStatus,
  type SmsMarketingTriggerSource,
  type UnreadCountResponse,
} from './notifications';

export {
  getPortalCase,
  getPortalMe,
  getPortalPushStatus,
  listPortalCaseDocuments,
  listPortalCaseMessages,
  listPortalCases,
  portalLogin,
  portalRefresh,
  provisionClientPortalUser,
  sendPortalCaseMessage,
  subscribePortalPush,
  unsubscribePortalPush,
  uploadPortalCaseDocument,
  getClientPortalUser,
  updateClientPortalUser,
  revokeClientPortalUser,
  type ClientPortalUser,
  type PortalCaseDetail,
  type PortalCaseDocumentsResponse,
  type PortalCaseMessageThread,
  type PortalCaseProgressResponse,
  type PortalCaseStage,
  type PortalCaseStatus,
  type PortalCaseSummary,
  type PortalDocument,
  type PortalLoginInput,
  type PortalMeResponse,
  type PortalPushStatus,
  type PortalPushSubscribeInput,
  type PortalPushSubscription,
  type PortalThreadMessage,
  type PortalTokenResponse,
  type ProvisionPortalUserInput,
  type SendPortalMessageInput,
  type UpdatePortalUserInput,
  type UploadPortalCaseDocumentInput,
} from './portal';

export interface HealthResponse {
  status: string;
  version: string;
  environment: string;
}

export interface VersionResponse {
  version: string;
  name: string;
}

export async function getHealth(): Promise<HealthResponse> {
  return request<HealthResponse>(apiPath('/health'), { auth: false });
}

export async function getVersion(): Promise<VersionResponse> {
  return request<VersionResponse>(apiPath('/version'), { auth: false });
}
