import { apiPath, request } from './http';

export {
  ApiClientError,
  ApiNotImplementedError,
  apiPath,
  configureApiClient,
  getAccessToken,
  getApiBaseUrl,
  notImplemented,
  request,
  setAccessToken,
  uploadRequest,
  type ApiClientConfig,
  type RequestOptions,
} from './http';

export {
  getCurrentUser,
  login,
  refreshToken,
  type LoginRequest,
  type RefreshTokenRequest,
  type TokenResponse,
  type User,
} from './auth';

export {
  getDashboard,
  type DashboardAccounts,
  type DashboardAlertItem,
  type DashboardAlerts,
  type DashboardAlertSeverity,
  type DashboardAlertType,
  type DashboardCases,
  type DashboardDocuments,
  type DashboardOperations,
  type DashboardOverview,
  type DashboardPerformance,
  type DashboardProcessing,
  type DashboardResponse,
  type DashboardTasks,
  type DashboardTimelineItem,
} from './dashboard';

export {
  getBureauPerformanceReporting,
  getEnterpriseReportingStatus,
  getMaterializedReportingStatus,
  getOperationsReporting,
  getPredictiveAnalyticsStatus,
  getPredictiveOutcomesReporting,
  getRevenueAnalyticsReporting,
  getTeamProductivityReporting,
  listMaterializedReportingRefreshRuns,
  refreshMaterializedReportingViews,
  refreshPredictiveOutcomesReporting,
  type BureauPerformanceItem,
  type BureauPerformanceReporting,
  type BureauPerformanceReportingResponse,
  type ClientReportingMetrics,
  type EnterpriseReportingStatus,
  type MaterializedReportingStatus,
  type NotificationReportingMetrics,
  type OperationsReporting,
  type OperationsReportingResponse,
  type PredictiveAnalyticsStatus,
  type PredictiveOutcomeRefreshResult,
  type PredictiveOutcomeRefreshRun,
  type PredictiveOutcomes,
  type PredictiveOutcomesReportingResponse,
  type ReportingMvRefreshResult,
  type ReportingMvRefreshRun,
  type RevenueAnalytics,
  type RevenueAnalyticsReportingResponse,
  type TeamMemberProductivity,
  type TeamProductivityReporting,
  type TeamProductivityReportingResponse,
} from './reporting';

export {
  createCase,
  deleteCase,
  generateCaseLlmSummary,
  getCase,
  listCases,
  updateCase,
  type Case,
  type CaseLlmSummary,
  type CreateCaseInput,
  type ListCasesParams,
  type UpdateCaseInput,
} from './cases';

export {
  createClient,
  createClientContact,
  deleteClient,
  deleteClientContact,
  getClient,
  getClientContact,
  listClientContacts,
  listClients,
  updateClient,
  updateClientContact,
  type Client,
  type ClientContact,
  type ClientStatus,
  type ContactRelationship,
  type CreateClientContactInput,
  type CreateClientInput,
  type ListClientContactsParams,
  type ListClientsParams,
  type UpdateClientContactInput,
  type UpdateClientInput,
} from './clients';

export { getLlmStatus, type LlmGateStatus } from './llm';

export {
  completeSsoEnrollment,
  confirmTotpEnrollment,
  disableTotpEnrollment,
  getEnterpriseIdentityStatus,
  getScimProvisioningStatus,
  getSsoEnrollmentStatus,
  getTotpEnrollmentStatus,
  listScimGroups,
  listScimUsers,
  provisionScimGroup,
  provisionScimUser,
  startSsoEnrollment,
  startTotpEnrollment,
  type EnterpriseIdentityStatus,
  type ScimGroupList,
  type ScimGroupProvisionInput,
  type ScimGroupResource,
  type ScimMeta,
  type ScimProvisioningStatus,
  type ScimUserList,
  type ScimUserProvisionInput,
  type ScimUserResource,
  type SsoEnrollmentComplete,
  type SsoEnrollmentCompleteInput,
  type SsoEnrollmentStart,
  type SsoEnrollmentStatus,
  type TotpEnrollmentStart,
  type TotpEnrollmentStatus,
} from './enterprise';

export {
  getBillingInvoicingStatus,
  getBillingStatus,
  getBillingUsageSummary,
  listBillingInvoicingRuns,
  recordBillingUsageEvent,
  runBillingInvoicingCycle,
  setupOrganizationBilling,
  subscribeOrganizationBilling,
  type BillingInvoicingRun,
  type BillingInvoicingRunInput,
  type BillingInvoicingRunKind,
  type BillingInvoicingRunResult,
  type BillingInvoicingStatus,
  type BillingSetupResponse,
  type BillingStatus,
  type BillingSubscribeInput,
  type BillingSubscribeResponse,
  type BillingUsageMetricTotal,
  type BillingUsageRecordInput,
  type BillingUsageRecordResponse,
  type BillingUsageSummary,
  type OrganizationBillingSummary,
  type SubscriptionStatus,
} from './billing';

export {
  createOrganizationApiKey,
  getApiKeyRateLimitStatus,
  getDeveloperPortal,
  getOrgAdminStatus,
  getOrganizationAdminSummary,
  getOrganizationApiKey,
  listOrganizationApiKeys,
  revokeOrganizationApiKey,
  rotateOrganizationApiKey,
  type ApiKey,
  type ApiKeyCreateInput,
  type ApiKeyCreateResponse,
  type ApiKeyRateLimitStatus,
  type ApiKeyRotateResponse,
  type ApiKeyScope,
  type DeveloperPortal,
  type OrgAdminStatus,
  type OrganizationAdminSummary,
} from './orgAdmin';

export {
  getCaseMessageThread,
  getMessagingCenterStatus,
  postCaseMessageThreadReply,
  type CaseMessageThread,
  type MessagingCenterStatus,
  type SendMessageInput,
  type ThreadMessage,
  type MessageSenderRole,
} from './messaging';

export {
  createConsentRecord,
  createRetentionPolicy,
  getComplianceCenterStatus,
  getConsentRecord,
  getRetentionEnforcementStatus,
  getRetentionPolicy,
  listConsentRecords,
  listRetentionEnforcementRuns,
  listRetentionPolicies,
  runRetentionEnforcement,
  updateRetentionPolicy,
  withdrawConsentRecord,
  type ComplianceCenterStatus,
  type ConsentRecord,
  type ConsentStatus,
  type ConsentType,
  type CreateConsentRecordInput,
  type CreateRetentionPolicyInput,
  type EnforcementRunStatus,
  type EnforcementTriggerSource,
  type ListConsentRecordsParams,
  type ListRetentionEnforcementRunsParams,
  type ListRetentionPoliciesParams,
  type RetentionEnforcementRun,
  type RetentionEnforcementRunResult,
  type RetentionEnforcementStatus,
  type RetentionPolicy,
  type RetentionScope,
  type UpdateRetentionPolicyInput,
} from './compliance';

export {
  createAccount,
  createAccountDisputeDraftReviewTask,
  createAccountDisputeLetterDraft,
  createAccountDisputeLetterReviewTask,
  approveAccountDisputeLetter,
  sendAccountDisputeLetter,
  voidAccountDisputeLetter,
  deleteAccount,
  getAccount,
  getAccountDisputeDraft,
  getAccountIntelligenceSummary,
  listAccountDisputeLetters,
  getAccountDisputeLetter,
  downloadAccountDisputeLetterExport,
  markAccountAwaitingDisputeResponse,
  markAccountDisputeResponseReceived,
  escalateAccountOverdueInvestigation,
  listAccounts,
  listCaseAccounts,
  updateAccount,
  type Account,
  type AccountDisputeDraft,
  type DisputeReasonSuggestion,
  type DisputeRecipientType,
  type DisputeResponseOutcome,
  type MissingEvidenceItem,
  type AccountIntelligenceSummary,
  type CreateAccountInput,
  type DisputeLetter,
  type DisputeLetterExportFormat,
  type DisputeLetterStatus,
  type ListAccountsParams,
  type NextActionItem,
  type UpdateAccountInput,
} from './accounts';

export {
  compareDocumentParsedCreditReport,
  confirmDocumentResolution,
  createDocumentParsedCreditReportReviewTask,
  deleteDocument,
  enqueueBatchDocumentSummaryRun,
  extractDocumentMetadata,
  generateDocumentLlmSummary,
  getBatchLlmSummaryStatus,
  getDocument,
  getDocumentDuplicateGroup,
  getDocumentDownloadUrl,
  getDocumentMetadata,
  getDocumentOcr,
  getDocumentParsedCreditReportAccountCandidates,
  getDocumentParsedCreditReport,
  getDocumentResolutions,
  listBatchDocumentSummaryRuns,
  listDocumentVersions,
  listDocuments,
  rejectDocumentResolution,
  resolveDocumentEntities,
  retryDocumentOcr,
  updateDocument,
  uploadDocument,
  uploadDocumentVersion,
  type BatchDocumentSummaryEnqueueResponse,
  type BatchDocumentSummaryRun,
  type BatchLlmSummaryStatus,
  type Document,
  type DocumentDuplicateGroup,
  type DocumentEntityResolution,
  type DocumentLlmSummary,
  type DocumentMetadata,
  type DocumentOcrResult,
  type DocumentParsedCreditReportAccountCandidates,
  type DocumentParsedCreditReport,
  type DocumentParsedCreditReportComparison,
  type DocumentResolutions,
  type DocumentVersion,
  type ListDocumentsParams,
  type ParsedReportAccountChange,
  type ParsedReportAccountCandidate,
  type ParsedReportComparisonSummary,
  type UpdateDocumentInput,
  type UploadDocumentInput,
} from './documents';

export {
  completeTask,
  createTask,
  deleteTask,
  getTask,
  listTasks,
  reopenTask,
  updateTask,
  type CreateTaskInput,
  type ListTasksParams,
  type Task,
  type UpdateTaskInput,
} from './tasks';

export {
  getTimelineEvent,
  listTimelineEvents,
  type ListTimelineParams,
  type TimelineEvent,
} from './timeline';

export {
  createNotification,
  getNotificationEmailDeliveryStatus,
  getNotificationSmsDeliveryStatus,
  getUnreadNotificationCount,
  listNotificationEmailDeliveries,
  listNotificationSmsDeliveries,
  listNotifications,
  markAllNotificationsRead,
  markNotificationRead,
  sendNotificationEmail,
  sendNotificationSms,
  type CreateNotificationInput,
  type EmailDeliveryAttempt,
  type EmailDeliveryLog,
  type EmailDeliveryStatus,
  type ListNotificationsParams,
  type Notification,
  type NotificationCategory,
  type SendNotificationEmailInput,
  type SendNotificationSmsInput,
  type SmsDeliveryAttempt,
  type SmsDeliveryLog,
  type SmsDeliveryStatus,
  type UnreadCountResponse,
} from './notifications';

export {
  getPortalCase,
  getPortalMe,
  getPortalPushStatus,
  listPortalCaseDocuments,
  listPortalCaseMessages,
  listPortalCases,
  portalLogin,
  portalRefresh,
  provisionClientPortalUser,
  sendPortalCaseMessage,
  subscribePortalPush,
  unsubscribePortalPush,
  uploadPortalCaseDocument,
  getClientPortalUser,
  updateClientPortalUser,
  revokeClientPortalUser,
  type ClientPortalUser,
  type PortalCaseDetail,
  type PortalCaseDocumentsResponse,
  type PortalCaseMessageThread,
  type PortalCaseProgressResponse,
  type PortalCaseStage,
  type PortalCaseStatus,
  type PortalCaseSummary,
  type PortalDocument,
  type PortalLoginInput,
  type PortalMeResponse,
  type PortalPushStatus,
  type PortalPushSubscribeInput,
  type PortalPushSubscription,
  type PortalThreadMessage,
  type PortalTokenResponse,
  type ProvisionPortalUserInput,
  type SendPortalMessageInput,
  type UpdatePortalUserInput,
  type UploadPortalCaseDocumentInput,
} from './portal';

export interface HealthResponse {
  status: string;
  version: string;
  environment: string;
}

export interface VersionResponse {
  version: string;
  name: string;
}

export async function getHealth(): Promise<HealthResponse> {
  return request<HealthResponse>(apiPath('/health'), { auth: false });
}

export async function getVersion(): Promise<VersionResponse> {
  return request<VersionResponse>(apiPath('/version'), { auth: false });
}
